### ISSUE TITLE
error

### ISSUE THREAD

**Issue by andycapcom** [iou90/react-native-autoheight-webview#1]
Hi I am getting an error when i try to run it on android:

undefined is not an object (evaluating '_reactNative.UIManager.RCTAutoHeightWebView.Commands')

**Comment by iou90** [comment]
I can not replicate this issue, what version of react-native-autoheight-webview you used and what version of your react-native & android sdk?

**Comment by iou90** [comment]
Linking this package may fixed the issue: react-native link react-native-autoheight-webview
