### ISSUE TITLE
enableAnimation={true} animationDuration={255} is not enabled

### ISSUE THREAD

**Issue by yhyfms** [iou90/react-native-autoheight-webview#10]

**Comment by iou90** [comment]
I can not replicate this issue, what version of react-native-autoheight-webview you used and what version of your react-native?

**Comment by yhyfms** [comment]
react native version is 0.43.3
react-native-autoheight-webview version is 0.2.3
and when set source={{ uri: "https://m.weibo.cn/1784473157/4133363868520464"}}, WebView is not work, why?

**Comment by iou90** [comment]
https://m.weibo.cn/1784473157/4133363868520464 seems to be a infinite scroll page, so the auto height function does not work here.
