### ISSUE TITLE
0.11.0 not working with Expo

### ISSUE THREAD

**Issue by rondublin** [iou90/react-native-autoheight-webview#102]
Hi

iOS seems great but Expo android version erroring with - 
**Device: (1053:881) Unable to resolve module 'module://react-native-autoheight-webview/autoHeightWebView/propTypes.js'
  Evaluating module://react-native-autoheight-webview/autoHeightWebView/propTypes.js
  Evaluating module://react-native-autoheight-webview.js**

Does the latest version support android on expo.  It's stated that 0.11.0 is pure js.

Thanks

**Comment by iou90** [comment]
Could you try with 1.0.0?
May be this will help: https://forums.expo.io/t/not-possible-to-use-react-native-webview/16141/5
