### ISSUE TITLE
Data loading slowly in Modal Android 

### ISSUE THREAD

**Issue by Anjy123** [iou90/react-native-autoheight-webview#104]
I'm using this package in Modal to render the Modal content, but in android the data is loading slowly e.g. 3-4 seconds, the content in the modal is dynamic. 

RN version : 57.8
react-native-autoheight-webview: 1.0.1

What can be the issue ?

**Comment by iou90** [comment]
Use react-native-webview and check whether the issue exists.

**Comment by Anjy123** [comment]
Can you please let me know what is the difference between this & react-native-webview?

**Comment by iou90** [comment]
@Anjy123 
This package now use react-native-webview instead of webview of react-native.

**Comment by Anjy123** [comment]
@iou90 1 more thing, in usage,  `react-native link react-native-webview` is written, this should be react-native link `react-native-autoheight-webview`, Am I correct?

**Comment by iou90** [comment]
@Anjy123 No.
