### ISSUE TITLE
Error: Unable to open URL: file:///var/containers/Bundle/Application/E2AB4E41-ADE4-460B-8D97-DFB13866C4D0/bszh.app/web

### ISSUE THREAD

**Issue by KGDeveloper** [iou90/react-native-autoheight-webview#105]
I'm an ios developer，Here's the error message I used
Error: Unable to open URL: file:///var/containers/Bundle/Application/E2AB4E41-ADE4-460B-8D97-DFB13866C4D0/bszh.app/web
I don't know if it was an environmental error or a clerical error，That's the way I write it
import React, { PureComponent } from 'react'
import { View, Text, StyleSheet,Platform ,Dimensions} from 'react-native'
import AutoHeightWebView from 'react-native-autoheight-webview'

export default class WebView extends PureComponent {
    render() {

        const {
            content,
            scalesPageToFit,
            scalePoint,
            initialScale,
            style
        } = this.props
        const headerString = initialScale
            ? `<head><meta name="viewport" content="width=device-width, initial-scale=${initialScale}"></head>`
            : ''
        return (
                <AutoHeightWebView
                    style={{ width: Dimensions.get('window').width - 15, marginTop: 35 }}
                     source={{
                         html: `
                     <!DOCTYPE html>
                     <html>${headerString}
                     <body>${content}
                     <script>window.onload=function(){ window.location.hash = '#' + document.body.clientHeight;document.title = document.body.clientHeight;}</script>
                     </body>
                     </html>`,
                         baseUrl: ''
                     }}
                    customScript={this.props.script}
                    
                    scrollEnabled={true}
                    scalesPageToFit={Platform.OS ==='ios'?true:false}
                    scalePoint={scalePoint}

                />
        )

    }
}

WebView.defaultProps = {
    scalesPageToFit:true,
    scalePoint: 1,
    initialScale: 0
}

const styles = StyleSheet.create({
    container: {
        flex: 1
    }
})

**Comment by KGDeveloper** [comment]
I wish I could get some help

**Comment by iou90** [comment]
I can not replicate this issue with the demo, could you replicate it with rn webview or react-native-webview instead?

**Comment by KGDeveloper** [comment]
I use react-native webview to display HTML, but react-native-autoheight-webview does not display my page

**Comment by KGDeveloper** [comment]
"react": "16.6.3", "react-native": "0.58.4",
This is my project version, but the react-native-autoheight-webview I downloaded when I installed it is version 0.6.1

**Comment by iou90** [comment]
Sorry, 0.6.1 was not supported, please use the latest version.
