### ISSUE TITLE
Cannot be used in ScrollView

### ISSUE THREAD

**Issue by liganghui** [iou90/react-native-autoheight-webview#106]
If I nest the AutoHeightWebView in a ScrollView, some of it will be cropped when loading long data.
Did I use it improperly?

Example ：

![qq 20190221223345](https://user-images.githubusercontent.com/15844198/53177452-0d87ad80-362b-11e9-8638-1dc47c32c2c4.png)

```
 return (
      <View style={{flex:1}}>
       <ScrollView   style={{flex:1}} >
      <AutoHeightWebView
       // A long web page or html
        source={{ html:  '.......' }}
      />
      </ScrollView>
      </View>
    );
```

`

My version

```
 "react-native": "0.57.8",
  "react-native-autoheight-webview": "^1.0.1",
    Windows 10                                                                                                  
   CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor     
   Memory: 935.75 MB / 7.95 GB  
   Yarn: 1.13.0 - ~\AppData\Roaming\npm\yarn.CMD
   npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
   IDEs: Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5014246
```

**Comment by iou90** [comment]
What exactly is your html?

**Comment by liganghui** [comment]
It's just plain text.
You can access this url  :  https://news-at.zhihu.com/api/4/news/3892357
It has a "body"  property, which is what I use.

**Comment by liganghui** [comment]
I think this has nothing to do with HTML, because I changed the HMTL to a URL, and connected to a CNN news, this problem will also occur.

**Comment by iou90** [comment]
I can not replicate this issue with the value of body property in demo (height: 6635). The style of View or ScrollView may cause the problem. A uri source is an entirely different case.

**Comment by liganghui** [comment]
I reproduce this problem. It has nothing to do with the style, as long as it is nested in the ScrollView. But it seems to only appear in the Android emulator? There are no problems with my two phones, including the same Android as the emulator Version (8.0), this is strange...

demo

![qq 20190222204417](https://user-images.githubusercontent.com/15844198/53243416-ba713180-36e2-11e9-800b-60aac32f7234.png)

**Comment by liganghui** [comment]
I tested it separately with two computers. This problem is really reproduced when the Android emulator device is Nexus 5X API 26 (8.0). When I use the emulator for Nexus6 API 23 (6.0), this problem disappears.....
![9aa10d222c9f3657138dce1e721cd32f 0](https://user-images.githubusercontent.com/15844198/53281218-18902a00-3760-11e9-85a6-fc6728ea41a5.jpg)


![qq 20190223114200](https://user-images.githubusercontent.com/15844198/53281224-1f1ea180-3760-11e9-8f67-a63693889cd4.png)



PS :  Android simulator from android studio

**Comment by iou90** [comment]
I also reproduce this problem with the WebView of react-native-webview using  fixed width & height on the emulator (api 26, chrome webview version 58), so there is not much this lib can do with this issue.

**Comment by liganghui** [comment]
I found a similar issue in react-native-webview , Someone has proposed a solution, it may be useful, but I have not verified it yet.
https://github.com/react-native-community/react-native-webview/issues/298

**Comment by liganghui** [comment]
I have not found a good solution yet. But I know a way, in the webView, insert a JS, listen to the page load, wait for the page to complete, pass the page height to the outside, and then reset the height of the webview. This method works, but not elegant enough.
I hope this problem can be solved as soon as possible.

**Comment by iou90** [comment]
Prop onSizeUpdated will be helpful to apply your solution.

**Comment by liganghui** [comment]
I think AutoHeightWebView may have some problems.
When I use react-native-webview, the text can be loaded normally, but when I use react-native-autoheight-webview, the text is not displayed properly.

demo
![qq 20190228215944](https://user-images.githubusercontent.com/15844198/53571602-4e8c3e80-3ba4-11e9-98cb-b52171536503.png)
![qq 20190222204417](https://user-images.githubusercontent.com/15844198/53571603-4f24d500-3ba4-11e9-8385-bf337632a586.png)


version:
```
  "react": "16.6.3",
   "react-native": "0.58.5",
   "react-native-autoheight-webview": "0.11.0",
   "react-native-webview": "^5.2.1"
```

**Comment by liganghui** [comment]
The above method still has some problems. It seems that the webview controls the scrolling of the page, not the ScrollView, and the scrollbar display is not normal.
