### ISSUE TITLE
Height too low on short webview

### ISSUE THREAD

**Issue by NKlug** [iou90/react-native-autoheight-webview#108]
The height of the webview seems to be calculated too small in the following example:
```javascript
const WebContainer = styled(AutoHeightWebView)`
  margin: 0 8px;
  width: ${Dimensions.get('window').width - 2 * 8}px;
`
 <WebContainer
            source={{
              baseUrl: URL_PREFIX + OFFLINE_CACHE_PATH,
              html: renderHtml(content, files)
            }}
            allowFileAccess
            originWhitelist={['*']} 
            useWebKit
            scalesPageToFit={false}
            javaScriptEnabled

            dataDetectorTypes={'all'}
            domStorageEnabled={false}
            showsVerticalScrollIndicator={false}
            showsHorizontalScrollIndicator={false}

            renderError={this.renderError}

            onShouldStartLoadWithRequest={this.onShouldStartLoadWithRequest}
          />
```
  

The following happens:
![webview_autoheight](https://user-images.githubusercontent.com/22690812/54234850-458a5e00-4510-11e9-8b1f-9cba89caedee.gif)

The expected behavior is that there is no scrolling.
I tried around a little to fix this and I came up with the following: If I change [this](https://github.com/iou90/react-native-autoheight-webview/blob/master/autoHeightWebView/utils.js#L136) line to  
```javascript
height = Math.max(document.documentElement.clientHeight, document.documentElement.scrollHeight, document.body.clientHeight, document.body.scrollHeight);
```
the height seems to be calculated correctly and there is no scrolling.

**Comment by NKlug** [comment]
Ok, so apparently the problem was that we had `<p>` tags in the html code which had margins that were not respected in the calculation of the height. Giving the `wrapper` some vertical padding (like 1) and later subtracting it solves this, as in this case the margins are respected ([see here](https://www.w3.org/TR/CSS2/box.html#collapsing-margins) for reference).
Would you accept a PR for this?

**Comment by iou90** [comment]
Could you style <p> tag to solve this problem?

**Comment by alexandrecanuto** [comment]
For anyone that comes across this, @NKlug hit the spot. The easiest workaround for me was to wrap my HTML content (whatever it was) in a container with 1px vertical padding:

```
  const descriptionStyle = `
    .html-container {
      padding-top: 1px;
      padding-bottom: 1px;
    }
  `;
 
  /**
   * Adds an HTML container to the passed HTML.
   */
  addHTMLContainer(html) {
    return `<div class="html-container">${html}</div>`;
  }

  render() {
    const { contentHTML } = this.props;
    const containerHTML = this.addHTMLContainer(contentHTML);

    return (
      <View style={styles.details}>
        <AutoHeightWebView source={{containerHTML}} customStyle={descriptionStyle} />
      </View>
    );
  }
```
