### ISSUE TITLE
Importing webview from 'react-native-webview' error

### ISSUE THREAD

**Issue by AmmarMZ** [iou90/react-native-autoheight-webview#118]
Error occurs in index.js

**Comment by iou90** [comment]
Any details?

**Comment by AmmarMZ** [comment]
Yeah in your index.js you are importing { WebView } from 'react-native-webview' when it should be from 'react-native'.

**Comment by AmmarMZ** [comment]
Also on an unrelated note, how do I implement the component into a class? I'm getting an error saying hooks must be defined in a function. Do you have an example project which uses it?

**Comment by iou90** [comment]
versioning
npm install react-native-autoheight-webview --save (rn >= 0.59, be capable of Hooks)

npm install react-native-autoheight-webview@1.0.1 --save (0.57 <= rn < 0.59)

Read README_old for earlier version guide.

This lib use react-native-webview from version 1.0.0 cause of Webview from rn was deprecated in 0.57 and it was removed in 0.60 https://github.com/react-native-community/releases/blob/master/CHANGELOG.md.

So you have to install react-native-webview before using this lib.

The rewrite with using hooks in this lib from version 1.1.0 does not mean it can not be used in a class component, for more information about react hooks: https://reactjs.org/docs/hooks-intro.html
