### ISSUE TITLE
cannot use custom font from local file

### ISSUE THREAD

**Issue by MoudiZd** [iou90/react-native-autoheight-webview#119]
@iou90 

Hello !
I am using your library on **ios**

I have this component

```
import React,{Component} from 'react';
import {View,ActivityIndicator,Dimensions} from 'react-native';
import AutoHeightWebView from 'react-native-autoheight-webview';

class DynamicWebView extends Component
    {
        constructor(props)
            {
                super(props);
                this.state = 
                    {
                        height: 0
                    }
                this.mycontext = this.props.context;
            }
        onWebViewMessage = (size) =>
            {
                if(size.height > 0)
                    {
                        this.mycontext.setState({height: parseInt(size.height)});
                        this.setState({height: parseInt(size.height)})
                    }
            }
        render()
            {
                let wrapperStyle = this.props.wrapperStyle || " style='direction:rtl;font-size: 19px;font-family: ae_AlArabiya;color: #666666;padding: 7px;'";
                let content = this.props.content || '';
                let style = this.props.style || {};
                let height = this.state.height && parseInt(this.state.height)>=0?this.state.height:200;
                let css = `<style type="text/css"> @font-face {font-family: ae_AlArabiya; src:url(file:///assets/fonts/ae_AlArabiya.ttf);} *{font-family: ae_AlArabiya}</style>`;
                return(<AutoHeightWebView
                    style={[{ width: Dimensions.get('window').width, marginTop: 35,backgroundColor: '#ffffff'},style]}
                    customStyle={`@font-face {font-family: ae_AlArabiya;src:url(file:///assets/fonts/ae_AlArabiya.ttf);} * {font-family: ae_AlArabiya;}`}
                    onSizeUpdated={(size) => {this.onWebViewMessage(size);}}
                    source={{html:  css + "<div" + wrapperStyle + ">"+ content + "</div>"}}
                    zoomable={false}
                    baseUrl=""
                    startInLoadingState={true}
                    renderLoading={() => <ActivityIndicator />}
                    />);
            }
    }
export default DynamicWebView;
```

i tried all ways to make my webview use font ae_AlArabiya but without any success.

Note : This was succeeded for normal react-native -webview

I attached a zip file that contains the font

Hope that their is any solution

Thank you in advance for any regards !

[ae_AlArabiya.ttf.zip](https://github.com/iou90/react-native-autoheight-webview/files/3380631/ae_AlArabiya.ttf.zip)

**Comment by MoudiZd** [comment]
I believe that the problem is with `baseurl` and the way the webview load assets
Now i tried to replace the local url with a remote url 

i replaced
`url(file:///assets/fonts/ae_AlArabiya.ttf)`
by 
`url(https://arbfonts.com/wp-content/fonts/new-arabic-fonts//22326-alarabiyafont.ttf)`

This solved the problem

But i need to load the font from local assets i don't want to load it remotely

**Comment by iou90** [comment]
```
    // 'file:///android_asset/web/' by default on android, 
    // web/' by default on iOS
    baseUrl: 'webAssets/',
    /* 
    use local or remote files
    to add local files: 
    add baseUrl/files... to android/app/src/assets/ on android
    add baseUrl/files... to project root on iOS
    */
    files={[{
        href: 'cssfileaddress',
        type: 'text/css',
        rel: 'stylesheet'
    }]}
```

**Comment by MoudiZd** [comment]
Thank you for replying quickly

Is webassets a mandatory name? Or it is the name of my folder whic is assets?

Because i tried to set it to the name of my folder `assets/` but without success

Also how i must drfine my font face within the css file???

Must i usr the font name without path???

Thank you in advance for any regards

**Comment by iou90** [comment]
@MoudiZd The base URL to be used for any relative links in the HTML, and you have to use files property to provide the relative address of them.
This so may be helping: https://stackoverflow.com/questions/33506908/react-native-webview-load-from-device-local-file-system

**Comment by tapannathvani** [comment]
can you please add an example that how to load custom fonts from local ? even we are facing the same issue.

<AutoHeightWebView
                                customStyle={`
                                           * {
                                            font-family: 'Poppins-SemiBold';
                                              }
                                            p {
                                            font-size: 15px;
                                               }
                                        `}

                                source={{ html:this.state.Book }} />

**Comment by sislovesmedotcom** [comment]
+1

**Comment by iou90** [comment]
@tapannathvani @sislovesmedotcom 
Now the local custom font example is included within the demo.

**Comment by lamaj411** [comment]
anybody can share some example code here, i checked the demo, but i cant understand bcz i am not an expert, please help me...
