### ISSUE TITLE
undefined is not an object

### ISSUE THREAD

**Issue by ioer2008** [iou90/react-native-autoheight-webview#12]
![qq 20170728102419](https://user-images.githubusercontent.com/12724988/28699914-04361a20-737f-11e7-90d8-bd5331ee50fc.png)
undefined is not an object

**Comment by iou90** [comment]
I can not replicate this issue, what version of react-native-autoheight-webview you used and what version of your react-native?

**Comment by ephor** [comment]
I have the same error. 

"react-native": "^0.46.1",
"react-native-autoheight-webview": "^0.2.5",

**Comment by samridhgupta** [comment]
same error.
