### ISSUE TITLE
Taking time to load the content in the webview

### ISSUE THREAD

**Issue by saikiranoptisol** [iou90/react-native-autoheight-webview#120]
After every click action of a button i need to change the content of webview which is taking time to load. As i check in [link](https://github.com/iou90/react-native-autoheight-webview/issues/104)  the solution is not provided but it is closed

**Comment by iou90** [comment]
Please use react-native-webview with fixed height and check whether the issue exists.

**Comment by saikiranoptisol** [comment]
@iou90  i used both react-native-webview and normal webview from reactnative with static height. at that time it is rendering fastly only. but i dont need static height. the height has to be changed based on content

**Comment by saikiranoptisol** [comment]
@iou90  can you please respond on this

**Comment by iou90** [comment]
@saikiranoptisol Please provide more details on your case.

**Comment by saikiranoptisol** [comment]
i have to render multiple choice questions and answers which is coming in a html content. for rendering options i will be using flatlist. In item of that flat list im using this autoheight webview to display html content. It displays correctly but it takes time to load the content even for basic text. I understand during image it takes time to load because of the size of the image. but even normal text is taking time to load. if i use normal webview instead of this component everything works fine but the height of the webview wont increase based on the HTML content.

**Comment by iou90** [comment]
@saikiranoptisol Could you provide a demo to reproduce it?

**Comment by saikiranoptisol** [comment]
@iou90  i can able to create a demo in snack because it is not taking auto-height-webview when i add it in package.json in expo snack

**Comment by iou90** [comment]
@saikiranoptisol I mean the demo which contains "multiple choice questions and answers which is coming in a html content" and will reproduce the slow loading issue.

**Comment by saikiranoptisol** [comment]
@iou90  to reproduce the issue i tried creating a sample in snack in which i cant able to add this library. i can able to add i can send you the reproducable code. but demo video i can do it.

**Comment by iou90** [comment]
Please provide a minimal demo which can reproduce this issue.

**Comment by Pardeep03315** [comment]
Facing same issue ... Any Solution on this ?? This library is awesome..but loading time is too late...how to fix it

**Comment by iou90** [comment]
@Pardeep03315 Please provide your source property for reproducing the issue.
