### ISSUE TITLE
Need module support typescript

### ISSUE THREAD

**Issue by technicalopt** [iou90/react-native-autoheight-webview#121]
Hi pro,

As the entry, can you make it support typescript format?

thank you!

**Comment by iou90** [comment]
Does index.d.ts not work properly?

**Comment by msspshaw** [comment]
Just to point out - in your package, you aren't assigning your index.d.ts file as the type property.
A sample from one of my projects looks like so:
<code>"types": "lib/index.d.ts"</code> where my .d.t.s is generated into a lib folder. In your case it would just be <code>"types": "index.d.ts"</code>.

In addition, however, in your package.json you have this snippet.
<code>"files": [
    "index.js",
    "autoHeightWebView"
  ]</code>
This is a whitelist for what is included when you npm publish, which means that you aren't including the index.d.ts in your npm package.

**Comment by technicalopt** [comment]
@msspshaw , Thank you!

Yes, I created a component with index.js as your suggestion. 
But other way to register types, the 'index.d.ts' file not be created in node_module/react-native-autoheight-webview

![image](https://user-images.githubusercontent.com/47841277/61940173-10fad880-afbf-11e9-8349-fc96ca47f286.png)

My version is 1.1.4

**Comment by technicalopt** [comment]
Also, as @msspshaw said, @iou90 please add "types": "index.d.ts", in your package.json

**Comment by iou90** [comment]
Should be fixed in version 1.1.6

**Comment by technicalopt** [comment]
@iou90 , It work perfectly on RN 0.60
