### ISSUE TITLE
Getting the following error message: Error evaluating injectedJavaScript: This is possible due to an unsupported return type. Try adding true to the end of your injectedJavaScript string.

### ISSUE THREAD

**Issue by AmmarMZ** [iou90/react-native-autoheight-webview#126]
![image](https://user-images.githubusercontent.com/22208012/61999418-50dcc100-b08e-11e9-9137-a11da5fa1b73.png)

In the node_modules auto-height-webview folder I commented out the highlight line and the error message stopped occurring. 

This is my package.json: 
"dependencies": {
    "@react-native-community/async-storage": "^1.4.1",
    "@react-navigation/core": "3.4.1",
    "@shoutem/ui": "^0.24.1",
    "expo": "^33.0.7",
    "expo-cli": "^3.0.2",
    "expo-file-system": "~5.0.1",
    "expo-linear-gradient": "~5.0.1",
    "expo-sharing": "~5.0.1",
    "fuse.js": "^3.4.5",
    "global": "^4.4.0",
    "lodash": "^4.17.11",
    "moment": "^2.24.0",
    "pdf-parse": "^1.1.1",
    "prop-types": "^15.7.2",
    "react": "16.8.3",
    "react-dom": "^16.8.6",
    "react-native": "https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz",
    "react-native-autoheight-webview": "^1.1.5",
    "react-native-elements": "^1.1.0",
    "react-native-fs": "^2.13.3",
    "react-native-reanimated": "1.0.1",
    "react-native-webview": "5.8.1",
    "react-navigation": "^3.9.1",
    "react-navigation-redux-helpers": "^3.0.2",
    "react-redux": "^6.0.1",
    "redux": "^4.0.1",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0",
    "schedule": "0.4.0",
    "url": "^0.11.0",
    "uuid": "^3.3.2"
  },

**Comment by iou90** [comment]
FYI: https://github.com/react-native-community/react-native-webview/issues/341

**Comment by davidcort** [comment]
I use this property. I have this code and works.

`  const notHeader = `setTimeout(() => {
                            function notHeader(){
                                var header = document.querySelector('header');
                                    header.setAttribute('style','display:none !important');
                                    header.style.display = 'none';
                            }
                            notHeader();
                            return true;
                           },30);``
` <WebView 
                    ref={ref => this.webview = ref}
                    source={{uri: link }}
                    injectedJavaScript={notHeader}
                    originWhitelist={['*']}
                    ...
`
