### ISSUE TITLE
Size is not auto update when the content changes size after loading the initial contents

### ISSUE THREAD

**Issue by Manigandan-Azure** [iou90/react-native-autoheight-webview#127]
@iou90 How to auto update when the content changes size after loading the initial contents? I used  onSizeUpdated={size => console.warn(size.height)} to check the size but the height and width not changing at all

**Comment by KendoJaaa** [comment]
face the same problem

**Comment by KendoJaaa** [comment]
@Manigandan-Azure  have you found any workaround? 
I'm using Expo, not sure it's related.

**Comment by Manigandan-Azure** [comment]
@KendoJaaa Nope. I ended up using default webview with 100% height and added my contents as html instead

**Comment by KendoJaaa** [comment]
@Manigandan-Azure  you mean the following detail is in the web instead of in the react native app?

**Comment by Manigandan-Azure** [comment]
@KendoJaaa yes

**Comment by iou90** [comment]
More details about your case (html content, how to trigger the size changing)?

**Comment by iou90** [comment]
@Manigandan-Azure Could you mail me your html code?

**Comment by ManigandanRaamanathan** [comment]
> More details about your case (html content, how to trigger the size changing)?

@iou90 I wasn't able to auto trigger the size changing. However, instead of adding my react code below the html component, I decided to replicate the react javascript code into html and added inside the html component where I wanted.

**Comment by iou90** [comment]
@ManigandanRaamanathan Could you provide an example for the using?

**Comment by 349989153** [comment]
https://github.com/iou90/react-native-autoheight-webview/blob/master/autoHeightWebView/index.js#L67

@iou90 this happened because the calculated height will be overwrote by `this.props.style.height`. So even if the `setSize` get called, the change will not happened

**Comment by iou90** [comment]
@349989153 @Manigandan-Azure @KendoJaaa You can update the size depending on the value from onSizeUpdate callback.
