### ISSUE TITLE
iOS Deprecated API Usage Warning, have to remove UIWebView

### ISSUE THREAD

**Issue by LekZ974** [iou90/react-native-autoheight-webview#128]
Just submitted my app to TestFlight and got an email with the error:

> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

react-native-webview make an update to remove this warning.
[https://github.com/react-native-community/react-native-webview/releases]()

**Comment by iou90** [comment]
So updating react-native-webview still not solve your problem?
