### ISSUE TITLE
onSizeUpdated is called continuously when it contains table in HTML

### ISSUE THREAD

**Issue by uday5162** [iou90/react-native-autoheight-webview#129]

**Comment by iou90** [comment]
More details about your case (html content, output of onSizeUpdated)?

**Comment by uday5162** [comment]
This is the html code.
```
<table border="1" cellpadding="1" cellspacing="1" style="height:100%; width:100%">
	<tbody>
		<tr>
			<td>Some Content</td>
			<td>Some Content</td>
		</tr>
		<tr>
			<td>Some Content</td>
			<td>Some Content</td>
		</tr>
		<tr>
			<td>Some Content</td>
			<td>Some Content</td>
		</tr>
		
	</tbody>
</table>
```
if it is because of the style height 100%
I tried to override its height auto !important tag (no use)

**Comment by uday5162** [comment]
onSizeUpdated is being called continuously.
Are you able to reproduce the issue?

**Comment by uday5162** [comment]
Hello,

As the html content comes dynamically in my project .I used regex and removed the height:100% which is working fine.
