### ISSUE TITLE
navState.title return result  still is 0 in IOS, why?

### ISSUE THREAD

**Issue by yhyfms** [iou90/react-native-autoheight-webview#13]
<WebView
                    style={Styles.webView}
                    injectedJavaScript={script + customScript}
                    scrollEnabled={false}
                    javaScriptEnabled={true}
                    source={webViewSource}
                    onNavigationStateChange={this.handleNavigationStateChange} />

handleNavigationStateChange(navState) {
        const height = Number(navState.title);
        if (height) {
            if (this.props.enableAnimation) {
                this.opacityAnimatedValue.setValue(0);
            }
            this.setState({ height }, () => {
                if (this.props.enableAnimation) {
                    Animated.timing(this.opacityAnimatedValue, {
                        toValue: 1,
                        duration: this.props.animationDuration
                    }).start(() => this.onHeightUpdated(height));
                }
                else {
                    this.onHeightUpdated(height);
                }
            });
        }
    }

navState.title return result  still is 0 in IOS, why?

**Comment by iou90** [comment]
please provide your source.
