### ISSUE TITLE
Not working on android

### ISSUE THREAD

**Issue by KestasVenslauskas** [iou90/react-native-autoheight-webview#134]
So I have this iframe. It's a facebook comments iframe.
{url} = any url.

basicaly it works on ios. On android you see only section where you can add comment.
If there is comments on this url it will not be visible on android.

for example you can use this url: https://developers.facebook.com/docs/plugins/comments#configurator

```
    <iframe src="http://www.facebook.com/plugins/comments.php?href={url}"
    scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:430;
    allowTransparency="true"></iframe>
```

**Comment by KestasVenslauskas** [comment]
Update: Not working on iOS also. Only on emulator

**Comment by iou90** [comment]
Writing within a plain html file:
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>test</title>
  </head>
  <body>
    <iframe
      src="http://www.facebook.com/plugins/comments.php?href=https://developers.facebook.com/docs/plugins/comments#configurator"
      scrolling="no"
      frameborder="0"
      style="border:none; overflow:hidden; width:430;"
      allowTransparency="true"
    ></iframe>
  </body>
</html>
```

and `document.body.offsetHeight` is 154

**Comment by KestasVenslauskas** [comment]
Yes exactly 154 without any comments. But there should be visible comments;

**Comment by iou90** [comment]
@KestasVenslauskas 
I mean it's not a problem of this lib, there is no comments although within a plain html file.
