### ISSUE TITLE
Invariant violation:Invariant violation hooks can only be called inside the body of a function component

### ISSUE THREAD

**Issue by bigkrys** [iou90/react-native-autoheight-webview#138]
react-native：0.58.6
运行demo即出现该问题，具体报错如下图
![image](https://user-images.githubusercontent.com/17899020/68753587-43991180-0640-11ea-9b05-71a4e70faf0f.png)
![image](https://user-images.githubusercontent.com/17899020/68753610-48f65c00-0640-11ea-8c17-bc6b4d56629e.png)

**Comment by iou90** [comment]
rn 0.58 is not capable with Hooks.
