### ISSUE TITLE
[android] 5.1 不显示

### ISSUE THREAD

**Issue by liuxiaofan** [iou90/react-native-autoheight-webview#139]
Android5.1
用scrollview包裹react-native-autoheight-webview，在Android5.1上不显示，只有给react-native-autoheight-webview加上一个高度才显示，在新版的Android中没有这个问题，请问有什么解决方案么？
"react-native": "0.61.2",
"react-native-autoheight-webview": "^1.3.0"

**Comment by iou90** [comment]
It's a problem which arrow function not supported below android 6.0 since @1.2.4, should be fixed on @1.3.1.
https://github.com/iou90/react-native-autoheight-webview/releases

**Comment by bashen1** [comment]
测试了下，Android下，如果webview在FlatList中也无法高度，好像handlemessage没有执行，iOS可以。感觉是0.6X的缘故

**Comment by iou90** [comment]
@bashen1 Does the demo works but not in your app with FlatList?

**Comment by nolife08021** [comment]
@iou90  hi, autoheight-webview not displaying content while inside the scroll view.  Kindly advice.

"react-native": "0.59.5",
"react-native-autoheight-webview": "^1.3.1",



`<ScrollView ref="myRef" style={{ flex:1 , backgroundColor:'white'}}>`
` <View style={{flex:9, marginRight:10, padding:5}}>`

`<AutoHeightWebView
          style={{ width: Dimensions.get('window').width - 15, marginTop: 35 }}
          onSizeUpdated={(size) => console.log(size.height)}
          files={[{
              href: 'cssfileaddress',
              type: 'text/css',
              rel: 'stylesheet'
          }]}
          source={{  html: html }}
          scalesPageToFit={true}
        />`

`</View>`
`</ScrollView>`

**Comment by iou90** [comment]
@nolife08021 please open a new issue.

**Comment by nolife08021** [comment]
@iou90  okay

**Comment by liuxiaofan** [comment]
谢谢，完美解决
