### ISSUE TITLE
When scrollEnabled=false and zoomed-in enable scroll

### ISSUE THREAD

**Issue by 0nn0** [iou90/react-native-autoheight-webview#143]
Hi iou90,

When `scrollEnabled=false` it would be great that when zoomed-in one could scroll horizontally and vertically. 

Use case: font-size of rendered content is too small. I'd like to be able to zoom-in a little and scroll through the content.

**Comment by iou90** [comment]
Please check this branch: https://github.com/iou90/react-native-autoheight-webview/tree/scrollWhenZoomin

``` javascript
<AutoHeightWebView
        scrollableWhenZoomin
        scrollEnabled={false}
```

**Comment by 0nn0** [comment]
Great! It pretty much works, except for two things...

1. Sometimes it suddenly starts scaling again from the corner, see at the end of this video: https://www.loom.com/share/49fbcdbb23a9450c930524e66d6848f2

2. Is there a way to pan diagonally when zoomed-in? Not sure whether this is a limitation in `react-native-webview`

**Comment by iou90** [comment]
1. I can not get what' going wrong from that video.
2. Panning works well when zoomin.

**Comment by 0nn0** [comment]
1. For me it is also difficult to reproduce the issue. I will keep an eye on it.
2. Also **diagonally**?

**Comment by iou90** [comment]
Also diagonally.
![diagonally panning](https://media.giphy.com/media/gJzEoqvrjxiX6VRMo8/giphy.gif)

**Comment by 0nn0** [comment]
Managed to reproduce the issue I had earlier. In the video below you see that the first time I scale up the webview that it scales it up from the top left which is not correct. The second time I scale it up further it does work correct.

To reproduce:
1. Zoom a tiny bit in
2. Zoom again and notice the difference

See 👇
https://www.loom.com/share/b17f9d1db90a4f03a3bece70c09dd6c7

Not sure whether it is related to react-native-autoheight-webview or to react-native-webview.

Thanks for the GIF of the diagonal movement. Does it also pan diagonally when you've zoomed-in and press/move with a single finger? Might be also a limitation of react-native-webview

**Comment by iou90** [comment]
There is an issue about top left scaling mentioned in react-native-webview repo: https://github.com/react-native-community/react-native-webview/issues/893.
As to pan diagonally with a single finger, I find it is difficult to do on iOS in almost every webview from different apps witch is mush easier on Andoird.
I think little things seems to help with this lib.

**Comment by 0nn0** [comment]
Thank you! Then let's close this issue.
