### ISSUE TITLE
How to prevent double-clicking and scrolling？

### ISSUE THREAD

**Issue by liuyunzyj** [iou90/react-native-autoheight-webview#145]
<AutoHeightWebView
       
                style={{ width: deviceWidth}}
                //customScript={`document.body.style.background = 'lightyellow';`}
                customStyle={`
                  p {
                    font-size: 32px;
                  }
                `}
                //  customScript={`document.body.style.background = 'lightyellow';`}
                bounces={false}
                javaScriptEnabled={true}
                source={{ html: getnewsinfo.description }}
                scalesPageToFit={true}
                zoomable={false}
                //onMessage={this.onMessage}
                onLoadProgress={({ nativeEvent }) =>
                  this.setState({ progress: nativeEvent.progress })
                }
              />

**Comment by iou90** [comment]
The zoomable prop only works on iOS when disable scalesPageToFit.
``` javascript
scalesPageToFit={false}
zoomable={false}
```

**Comment by liuyunzyj** [comment]
scalesPageToFit={false}The view cannot hold the width and will display incomplete

**Comment by liuyunzyj** [comment]
@iou90 How do you get to a normal display that only shows half of the original content

**Comment by iou90** [comment]
@liuyunzyj 
``` javascript
scalesPageToFit
viewportContent={'width=device-width, user-scalable=no'}
```
Above codes should work on iOS from v1.4.0.
Please note that 'width=device-width' with scalesPageToFit may cause some layout issues on Android, for these conditions, using __customScript__ prop to apply custom viewport meta.
FYI: 
https://github.com/react-native-community/react-native-webview/blob/master/docs/Reference.md#scalespagetofit
https://github.com/react-native-community/react-native-webview/blob/5b0c634f15dbf8eb8210d4393da9ca86df1de453/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
``` java
@ReactProp(name = "scalesPageToFit")
  public void setScalesPageToFit(WebView view, boolean enabled) {
    view.getSettings().setLoadWithOverviewMode(enabled);
    view.getSettings().setUseWideViewPort(enabled);
  }
```
https://developer.android.com/reference/android/webkit/WebSettings.html#setUseWideViewPort(boolean)
https://developer.android.com/reference/android/webkit/WebSettings.html#setLoadWithOverviewMode(boolean)
