### ISSUE TITLE
I'm hesitant to use it.Is UIWebView used?

### ISSUE THREAD

**Issue by wulala1997** [iou90/react-native-autoheight-webview#155]
**Bug description:**

**To Reproduce:**

**Source (static HTML or url):**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS:
 - OS version:
 - react-native version:
 - react-native-webview version:
 - react-native-autoheight-webview version:

**Comment by iou90** [comment]
Please check this issue https://github.com/iou90/react-native-autoheight-webview/issues/156.
