### ISSUE TITLE
are we using UIWebView?

### ISSUE THREAD

**Issue by girish54321** [iou90/react-native-autoheight-webview#156]
**Bug description:**
is this package  using UIWebView
**To Reproduce:**
i got mail form apple 
      Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs starting from April 2020
**Source (static HTML or url):**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS: Mac OS
 - OS version: 
 - react-native version:0.59.10
 - react-native-webview version: 7.5.2
 - react-native-autoheight-webview version:1.3.4

**Comment by iou90** [comment]
It has been removed since react-native-webview@7.0.1 (https://github.com/react-native-community/react-native-webview/releases/tag/v7.0.1).
Have you run "pod install" ?

**Comment by girish54321** [comment]
Thanks i will try this and will let you know if it works or not .. :-)

**Comment by girish54321** [comment]
I see no usage of UIWebView in this package .. thanks
