### ISSUE TITLE
React-native-autoheight-webview is not containing the android folder

### ISSUE THREAD

**Issue by litelo** [iou90/react-native-autoheight-webview#160]
**Bug description:**
The package react-native-autoheight-webview does not contain the android folder all other packages have this folder can anyone explain why as it is crashing my app

 

**Screenshots/Videos:**
Below is the error
![errrrrr](https://user-images.githubusercontent.com/27894559/78632645-30bbfd80-78bd-11ea-8a6c-a550aa9fda63.png)

Below is the screenshot of the package structure

![issue](https://user-images.githubusercontent.com/27894559/78674700-a21d9f80-7901-11ea-88cb-e00c19642a8c.png)

**Environment:**
 - OS: Windows
 - OS version: latest
 - react-native version: 0.62.1
 - react-native-webview version:9.1.0
 - react-native-autoheight-webview version:1.4.2

**Comment by iou90** [comment]
Do you want to use it in a Windows app or build on Windows? Sorry but currently there is no Windows supporting plan.
This lib is a pure js lib since v1.0.0

**Comment by litelo** [comment]
Yes I am using it to make and android app on windows. Actually I am working on a older project when it has windows support, so do you have any workaround  or should I stop using it

**Comment by iou90** [comment]
@litelo Does the problem remain when building on mac?

**Comment by litelo** [comment]
yes the problem persists in both the OS

**Comment by iou90** [comment]
I can not reproduce your issue with:
OS: Windows/Mac
OS version: latest
react-native version: 0.62.2
react-native-webview version: 9.1.0
react-native-autoheight-webview version: 1.4.2

But it does has some problems since react-native-webview@9.1.0, please check: https://github.com/iou90/react-native-autoheight-webview/releases/tag/v1.4.3
