### ISSUE TITLE
How to send data from react-native to H5 page?

### ISSUE THREAD

**Issue by JessieLau-CT** [iou90/react-native-autoheight-webview#161]
error tips:webView.postMessage() is not a function
`let webView: any = null;`
`<AutoHeightWebView
                        ref={refs => (webView = refs)}....`
and in my function l used `webView.postMessage("test");`
but it shows webView.postMessage() is not a function
l don't konw how to solve it.

**Comment by iou90** [comment]
With v1.5.0, you can use all methods of react-native-webview.

``` js
const web = useRef();
const action = () => web.current.injectJavaScript('postMessage...');
<AutoHeightWebview ref={web}
<Button onClick={action}
```

FYI: https://github.com/react-native-community/react-native-webview/blob/master/docs/Guide.md#the-injectjavascript-method
