### ISSUE TITLE
getRandomValues() Android Error

### ISSUE THREAD

**Issue by Conrador** [iou90/react-native-autoheight-webview#162]
**Bug description:**
Hi.
App Crashes on Android after updating to 1.4.3 version. 1.5.0 v does not fix the issue. 

**To Reproduce:**
Code: 
<img width="555" alt="Screenshot 2020-04-16 at 11 18 48" src="https://user-images.githubusercontent.com/31658644/79438675-2217c980-7fd4-11ea-9b67-3679c1ec4e8a.png">

**Source (static HTML or url):**
static HTML

**Expected behavior:**
App should not crash

**Screenshots/Videos:**
![Screenshot_1587028484](https://user-images.githubusercontent.com/31658644/79438423-c9483100-7fd3-11ea-8d0f-b891da2f7983.png)

**Environment:**
 - OS: Android
 - OS version: 10.0
 - react-native version: 0.62.2
 - react-native-webview version: 9.2.1
 - react-native-autoheight-webview version: 1.5.0

**Comment by iou90** [comment]
Please using react-native-webview@9.0.2 https://github.com/iou90/react-native-autoheight-webview/releases/tag/v1.4.3

**Comment by Conrador** [comment]
Unfortunately the same issue :(

**Comment by Conrador** [comment]
Works, Thanks. Waiting for react-native-webview to resolve the issue :)
