### ISSUE TITLE
Custom font is not working for both android and ios

### ISSUE THREAD

**Issue by sandeepg1220** [iou90/react-native-autoheight-webview#163]
Custom font is not working for HTML content. even normal font like Verdana also not working.
react-native - 0.62.1
react-native-autoheight-webview - 1.5.0
react-native-webview - 7.0.1(I checked with latest version also)

**Comment by iou90** [comment]
Does it works with react-native-webview only?

**Comment by hussainhspl** [comment]
@iou90 : any update ?

**Comment by deepak-jha-kgp** [comment]
Following is my code and it seems to work
`const html = "<div style='font-family:Muli-Regular' id="formula" style="visibility: hidden;width: 85%;">
			${content}
        </div>"`
`const css = "<head><style type="text/css"> @font-face {font-family: 'Muli-Regular'; src:url('file:///android_asset/fonts/Muli-Regular.ttf')}</style></head>"`

`const data= css + html`

And then I pass data to `AutoHeightWebView` as `source={{ html: data}}`

**Comment by iou90** [comment]
@hussainhspl 
I think it's a problem of react-native-webview, FYI: https://github.com/react-native-community/react-native-webview/issues/1247, https://github.com/react-native-community/react-native-webview/issues/1016

**Comment by hussainhspl** [comment]
@iou90 :  we will wait for webview to update

**Comment by sandeepg1220** [comment]
> Does it works with react-native-webview only?

it is working with react-native-webview

**Comment by iou90** [comment]
Verdana can actually works in demo.

**Comment by grs786** [comment]
DSari font is not supportable

**Comment by iou90** [comment]
@grs786 I can not test DSari cause of it's required to pay, and does Serif work with react-native-webview?

**Comment by iou90** [comment]
@grs786 Serif works in demo.

**Comment by girish54321** [comment]
same for me not working in `AutoHeightWebView` 
but `react-native-webview `works 


source={{
                  baseUrl: "",
                  html: `
                  <html>
                  <head>
                      <style>
                          ${generateAssetFontCss({
                            fontFileName: "DMSans-Regular",
                            extension: "ttf",
                          })}
                          * {
                            font-size: 17px;
                            max-width: ${WIDTH - 24};
                            line-height: 1.6;
                            font-family: DMSans-Regular !important;
                            color: ${dark ? "#fff" : null};
                            background-color: ${dark ? "#000" : null};
                          }
                          p {
                            margin-bottom: 16px;
                          }
                      </style>
                      <meta
                          name="viewport"
                          content="width=${WIDTH - 24}, user-scalable=on
                      />
                  </head>
                  <body style="padding:10px">
                  ${style + article.html_content}
                  </body>
                  </html>`,
                }}


`export const generateAssetFontCss = ({
  fontFileName,
  extension = "ttf",
}: {
  fontFileName: string;
  extension?: string;
}) => {
  const fileUri = Platform.select({
    ios: `${fontFileName}.${extension}`,
    android: `file:///android_asset/fonts/${fontFileName}.${extension}`,
  });

  return `@font-face {
      font-family: '${fontFileName}';
      src: local('${fontFileName}'), url('${fileUri}') ;
  }`;
};`

**Comment by iou90** [comment]
> same for me not working in `AutoHeightWebView`
> but `react-native-webview `works
> 
> source={{
> baseUrl: "",
> html: ` <html> <head> <style> ${generateAssetFontCss({ fontFileName: "DMSans-Regular", extension: "ttf", })} * { font-size: 17px; max-width: ${WIDTH - 24}; line-height: 1.6; font-family: DMSans-Regular !important; color: ${dark ? "#fff" : null}; background-color: ${dark ? "#000" : null}; } p { margin-bottom: 16px; } </style> <meta name="viewport" content="width=${WIDTH - 24}, user-scalable=on /> </head> <body style="padding:10px"> ${style + article.html_content} </body> </html>`,
> }}
> 
> `export const generateAssetFontCss = ({ fontFileName, extension = "ttf", }: { fontFileName: string; extension?: string; }) => { const fileUri = Platform.select({ ios: `${fontFileName}.${extension}`, android: `file:///android_asset/fonts/${fontFileName}.${extension}`,
> });
> 
> return `@font-face { font-family: '${fontFileName}'; src: local('${fontFileName}'), url('${fileUri}') ; }`;
> };`
> 
> but android works

Make sure your baseUrl is correct. 
"BaseUrl now contained by source. 'web/' by default on iOS; 'file:///android_asset/' by default on Android or uri."

**Comment by girish54321** [comment]
@iou90  Thanks for your replay and very nice package 
but the thing is if i don't want `BaseUrl ` and if i pass "" empty string then the screen is keeps loading 

I can share my code if you want more info. 👍🏽

**Comment by iou90** [comment]
@grs786 Better with both working codes using `react-native-webview` and not working codes using `react-native-autoheight-webview`, because this lib does nothing about `baseUrl`.

**Comment by girish54321** [comment]
There is no problem in package my code was wrong 
My bad 😥  😝
