### ISSUE TITLE
Multiple AutoHeightWebView components on same screen

### ISSUE THREAD

**Issue by deepak-jha-kgp** [iou90/react-native-autoheight-webview#165]
**Bug description:**
I have a use case where I need to render multiple `AutoHeightWebView `components within a single screen. 
But while doing so, I realized only the last component is getting rendered.
If I pass `height` manually to the parent  `View` component, I'm able to see the contents, but that defeats the purpose of this library for me. I've tried setting `flex:1, alignItems: 'stretch'` in both, parent `View` component and `AutoHeightWebView` but nothing seems to work if I don't set the height manually

**To Reproduce:**

`<View style={{padding: 1}}>
				<AutoHeightWebView
                    style={{width: 85*vw,alignItems:'stretch',}}
					source={{ html: html }}
					zoomable={false}					
				/>
			</View>`
`<View style={{padding: 1}}>
				<AutoHeightWebView
                    style={{width: 85*vw,alignItems:'stretch'}}
					source={{ html: html }}
					zoomable={false}					
				/>
			</View>`

**Source (static HTML or url):**
static HTML

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - react-native version:0.62.2
 - react-native-webview version:9.1.1
 - react-native-autoheight-webview version:1.5.1

**Comment by iou90** [comment]
Please try to upgrade react-native-webview to the last version.

**Comment by petkovv** [comment]
@deepak-jha-kgp Updradeing worked?
