### ISSUE TITLE
Can't resize the img tag in the html body

### ISSUE THREAD

**Issue by Bayramito** [iou90/react-native-autoheight-webview#171]
Hello,

Somehow i can't set the height for the img tags in the html data.

im getting data like :

`<p>some description</p><p><strong>title</strong></p><p><img alt="" src="image link" style="height:413px; width:750px" /></p><p>&nbsp;</p><p><img alt="src="another image" style="height:500px; width:750px" /></p>`

sometimes also getting iframes in the p tags. 

i can resize the iframes with
`customStyle={iframe{width: 400;  height:300;}}`

but i cant resize the images  with the same way.

**Comment by iou90** [comment]
```
customStyle={`img { width: 200px !important; height: 200px !important; }`}
```
