### ISSUE TITLE
content overflow on iOS

### ISSUE THREAD

**Issue by prabathRN** [iou90/react-native-autoheight-webview#177]
**Bug description:**

For some html pages the page is getting cut off on iOS devices

**To Reproduce:**

**Source (static HTML or url):**
static html

**Expected behavior:**

content should not overflow

**Screenshots/Videos:**

**Environment:**
 - OS: iOS
 - OS version: 13.6
 - react-native version:0.60.5
 - react-native-webview version: 10.4.0
 - react-native-autoheight-webview version:1.5.2

**Comment by iou90** [comment]
Please provide your HTML code.

**Comment by Donhv** [comment]
same issue

**Comment by iou90** [comment]
@Donhv Please show your HTML.

**Comment by prabathRN** [comment]
@iou90  <html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title></title>
</head>
<body><table width=100% border=0 BORDERCOLOR=RED CELLPADDING=0><TR><TD>
<div dir="ltr">
<div><img src="{{src of the gif file}}" alt="BD2.gif" width="542" height=
"304" /><br /></div>
</div>


</TD></TR></TABLE></BODY></HTML>

**Comment by prabathRN** [comment]
`<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title></title>
</head>
<body><table width=100% border=0 BORDERCOLOR=RED CELLPADDING=0><TR><TD>
<div dir="ltr">
<div><img src="file:///Users/kirithikaravi/Library/Developer/CoreSimulator/Devices/94B29FE1-1A92-4779-A05A-12CEF9F8DDC9/data/Containers/Data/Application/780687FA-8AFB-4304-A472-623F86771307/tmp/BD3.gif" alt="BD3.gif" width="542" height=
"304" /><br /></div>
</div>
​
​
</TD></TR></TABLE></BODY></HTML>
 `

**Comment by BojanRatkovic** [comment]
Yep, same problem here.
When i try to set horizontalPadding, the content on the right side is cut off.

**Comment by BojanRatkovic** [comment]
I manage to fix this.
Instead of this: `style={{ width: Dimensions.get('window').width - 15, marginTop: 35 }}`
Try this: `style={{ width: "100%" }}`

And my paddingHorizontal works just fine.

**Comment by prabathRN** [comment]
@BojanRatkovic still the same for me

**Comment by iou90** [comment]
> ```
> <html xmlns="http://www.w3.org/1999/xhtml">
> <head>
> <title></title>
> </head>
> <body><table width=100% border=0 BORDERCOLOR=RED CELLPADDING=0><TR><TD>
> <div dir="ltr">
> <div><img src="local path of file" alt="BD3.gif" width="542" height=
> "304" /><br /></div>
> </div>
> ​
> ​
> </TD></TR></TABLE></BODY></HTML>
> ```
> 
> @iou90

Can not reproduce the issue with:
react-native version: 0.63.0
react-native-webview version: 10.7.0
react-native-autoheight-webview version: 1.5.2
iOS: 13.6 (iPhone11)
Android: 10 api29 (Pixel3)

**Comment by iou90** [comment]
@prabathRN Is there a screenshot for this issue?

**Comment by prabathRN** [comment]
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-08-19 at 13 40 17](https://user-images.githubusercontent.com/22348767/90609649-ff1b5180-e221-11ea-990f-5eeca015d346.png)
@iou90  this is the screnshot from app

**Comment by prabathRN** [comment]
<img width="607" alt="Screen Shot 2020-08-19 at 1 46 23 PM" src="https://user-images.githubusercontent.com/22348767/90609945-62a57f00-e222-11ea-829d-8e23ae5093c7.png">
@iou90 this is original gif screenshot

**Comment by iou90** [comment]
@prabathRN 
I can not reproduce the issue with the image above (https://user-images.githubusercontent.com/22348767/90609945-62a57f00-e222-11ea-829d-8e23ae5093c7.png).

**Comment by podoglyph** [comment]
I had a similar issue with text where padding caused the text on the right side of the container to be cutoff. The following combination of styles on the component works.

```
style={{width: '100%'}}
containerStyle={{paddingHorizontal: 10}}
```
