### ISSUE TITLE
Doesn't work on Android

### ISSUE THREAD

**Issue by songhanlin** [iou90/react-native-autoheight-webview#18]
react native : 0.47.2
react-native-autoheight-webview: 0.3.1
--------
react-native run android 
than----->
node_modules/react-native-autoheight-webview/android/src/main/java/com/dscj/autoheightwebview/AutoHeightWebViewPackage.java:26: 错误: 方法不会覆盖或实现超类型的方法
    @Override
    ^
1 个错误
:react-native-autoheight-webview:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-autoheight-webview:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 10.427 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

**Comment by iou90** [comment]
sorry for this issue but I can not init a project with react native 0.47.2 cause of https://github.com/facebook/react-native/issues/14209

**Comment by songhanlin** [comment]
@iou90 can you try react-native 0.47.0? I change this version, 0.47.2 -> 0.47.0, failed too

**Comment by songhanlin** [comment]
@iou90 this version 0.47.0, ReactPackage.java removed 
`List<Class<? extends JavaScriptModule>> createJSModules(); ` method,
and your code AutoHeightWebViewPackage.java override this method

**Comment by songhanlin** [comment]
sorry about my bad english,  i try to delete this override method, than i run successfully , but i found another question, when i run myapp on genymotion , the img in the webview, bling bling bling ~~~, then i run on my android device (Huawei's phone), everything is ok.  i don't know why, can you help me?

**Comment by iou90** [comment]
0.3.2 fixed it and I can not help with your second question because I never run rn project on genymotion.

**Comment by hirani89** [comment]
Hi,

I am getting this issue with 0.6.1
here is my package.json
```
"dependencies": {
    "babel": "^6.23.0",
    "eslint": "^3.17.0",
    "lodash": "^4.17.10",
    "npm": "^6.1.0",
    "pretty-format": "^23.0.1",
    "prop-types": "^15.6.2",
    "react": "16.4.1",
    "react-native": "0.55.4",
    "react-native-app-link": "^0.4.1",
    "react-native-autocomplete-input": "^3.5.0",
    "react-native-autoheight-webview": "^0.6.1",
    "react-native-ci-tools": "^1.1.0",
    "react-native-elements": "^0.19.0",
    "react-native-expandable-section-list": "^1.0.7",
    "react-native-map-link": "^2.0.4",
    "react-native-maps": "^0.21.0",
    "react-native-navigation-directions": "^1.0.1",
    "react-native-phone-call": "^1.0.4",
    "react-native-snap-carousel": "^3.7.2",
    "react-native-tab-view": "^1.0.2",
    "react-native-vector-icons": "^4.5.0",
    "react-navigation": "^2.3.1"
  },
  "devDependencies": {
    "babel-core": "^6.26.3",
    "babel-jest": "^23.0.1",
    "babel-preset-react-native": "4.0.0",
    "jest": "23.1.0",
    "react-native-clean-project": "^2.0.0",
    "react-test-renderer": "16.3.1"
  },
```

**Comment by iou90** [comment]
@hirani89 please try the last version.
