### ISSUE TITLE
Question: AutoHeightWebView inside Flatlist

### ISSUE THREAD

**Issue by muhsinaldemir** [iou90/react-native-autoheight-webview#182]
As far as I understand in order to use AutoHeightWebView inside a Flatlist as a renderItem component we need to declare its height and width properties, which is similar with the original Webview where you can't use it inside a Flatlist without declaring a width and height. 

But since this project's main point is auto calculation of height, is it possible to use this inside a Flatlist without specifically declaring a height?

The code below just give a blank screen.
```javascript
            <FlatList
                data={['a', 'b', 'c']}
                keyExtractor={(item) => `${item}`}
                renderItem={({ item }) => {
                    return (
                        <AutoHeightWebView
                            source={{ html: `<p style="font-weight: 400;font-style: normal;font-size: 21px;line-height: 1.58;letter-spacing: -.003em;">Tags are great for describing the essence of your story in a single word or phrase, but stories are rarely about a single thing. <span style="background-color: transparent !important;background-image: linear-gradient(to bottom, rgba(146, 249, 190, 1), rgba(146, 249, 190, 1));">If I pen a story about moving across the country to start a new job in a car with my husband, two cats, a dog, and a tarantula, I wouldn’t only tag the piece with “moving”. I’d also use the tags “pets”, “marriage”, “career change”, and “travel tips”.</span></p>` }}
                        />
                    )
                }}
            />
```

But if I add the following line to the AutoHeightWebView I got what I expected but any content larger than 400 is causing problems as I specified the height statically.
```javascript
style={{ width: Dimensions.get('window').width - 40, height: 400 }}
```

### Expected Behaviour:

![webview](https://user-images.githubusercontent.com/38760332/91828503-e57a0100-ec48-11ea-8d5e-b8560303e833.jpeg)

### Question:
Is there any other way I could achieve the expected behaviour while AutoHeightWebView does height calculation?
Thanks in advance.

### Environment:

OS: Android
OS Version: 10
react-native version: 0.59.9
react-native-webview version: 10.3.2
react-native-autoheight-webview version: 1.5.3

**Comment by iou90** [comment]
``` javascript
<FlatList
  removeClippedSubviews={false}
```
May resolve the problem.

**Comment by muhsinaldemir** [comment]
@iou90 Thanks.  Solved the problem. I'm closing the issue now.

**Comment by ElChawich** [comment]
i still have same issue and the suggested fix didn't fix it for me on android
