### ISSUE TITLE
Infinite scroll of content observed for certain html content in Android

### ISSUE THREAD

**Issue by msuma268** [iou90/react-native-autoheight-webview#184]
**Bug description:** Infinite scroll of content observed for certain html content in Android

**To Reproduce:**

**Source (static HTML or url):**

const htmlContent= `<div dir="ltr"><br><br><div class="gmail_quote"><br><br><u></u>                                                                        <div bgcolor="#ffffff" style="margin:0!important;padding:0!important;font-family:Arial,sans-serif;font-size:15px;color:#343f44;word-break:break-word">        <div style="background-color:#ffffff" bgcolor="#ffffff">      <table cellpadding="0" cellspacing="0" style="border-spacing:0!important;border-collapse:collapse;margin:0;padding:0;width:100%!important;min-width:320px!important;height:100%!important" width="100%" height="100%">        <tbody><tr>          <td valign="top" style="border-collapse:collapse;font-family:Arial,sans-serif;font-size:15px;color:#343f44;word-break:break-word">            <div id="m_5127046700997499950hs_cos_wrapper_main" style="color:inherit;font-size:inherit;line-height:inherit">  <div id="m_5127046700997499950section_1585011864993" class="m_5127046700997499950hse-section m_5127046700997499950hse-section-1-col" style="padding-left:10px;padding-right:10px;padding-top:20px">                  <div class="m_5127046700997499950hse-column-container" style="min-width:280px;max-width:600px;width:100%;Margin-left:auto;Margin-right:auto;border-collapse:collapse;border-spacing:0;background-color:#ffffff" bgcolor="#ffffff">                <div id="m_5127046700997499950column_1585011864993_0" class="m_5127046700997499950hse-column">  <div id="m_5127046700997499950hs_cos_wrapper_module_15850118094532" style="color:inherit;font-size:inherit;line-height:inherit">	<table width="100%" cellpadding="0" cellspacing="0" style="border-spacing:0!important;border-collapse:collapse">    <tbody>        <tr>            <td align="center" valign="top" style="border-collapse:collapse;font-family:Arial,sans-serif;color:#343f44;word-break:break-word;text-align:center;padding:10px 20px;font-size:0px">                                    <a href="https://info.kobiton.com/e2t/c/*W3JnxRS5nyNFrW5V7M0P9knppg0/*W6rYL357PW6nXW11Q2Mv11nWlg0/5/f18dQhb0SbTR8YXNdxW8B6bkM50RnyCVqlGSk1hc8fSW1FSlSD56qZCNVcnTGj98ZjLLW5C9pvk4vgKM1W999f656PVKcrW6N3nBL8xGZLmW6bVLMX6bNbXjW16fCNc7cw-PTW203WCy2yJF1WVYT2jk6P4lCXW3WddQj6Pkt_VW62_rWz4MBwXVW4r1Pm71nq00dW95yjh38gjY6LW8WBKbV56sy_8W2NhXFJ6ghLm4W1B5NwB5pGYcDW1j3TgT2Rp6QwW5JWGGg4MBRVDW2MTwh75pfNr6W1WbnGk9ggJT5W4Q3JfF4P0jQtW54W4-_3mSVtZW3qJNCh5nDM6gW83PgZN4BWt5kW58tKx55ZRZgZW49Bd842M0f3_W5lsChZ5ZYGLqW49zVl_7JQLW8W9h3N-B2nmG_QW6Bklmz1dC8XQW4M11334H_8kLW2Nh_wb6yzJccW67VvMc1X1BW4W7l63H98k_VzVVb2_nM6PxM6PW12d7yM6z-hW1VlSbbV3kMS-ZW9cc62t2hC1TkW7gdd3-8v3WwgW1MWhN-1MKdbBf5xbpGV11" style="color:#00a4bd" target="_blank">                                <img alt="Kobiton logo" src="https://info.kobiton.com/hs-fs/hubfs/Logos/kobiton-logo.png?width=330&amp;upscale=true&amp;name=kobiton-logo.png" style="outline:none;text-decoration:none;border:none;max-width:100%;font-size:16px" width="165" align="middle">                                    </a>                            </td>        </tr>    </tbody></table></div></div>        </div>     </div>  <div id="m_5127046700997499950builtin_section-0" class="m_5127046700997499950hse-section m_5127046700997499950hse-section-1-col" style="padding-left:10px;padding-right:10px">                  <div class="m_5127046700997499950hse-column-container" style="min-width:280px;max-width:600px;width:100%;Margin-left:auto;Margin-right:auto;border-collapse:collapse;border-spacing:0;background-color:#ffffff;padding-bottom:40px;padding-top:40px" bgcolor="#ffffff">                <div id="m_5127046700997499950builtin_column_0-0" class="m_5127046700997499950hse-column">  <table cellpadding="0" cellspacing="0" width="100%" style="border-spacing:0!important;border-collapse:collapse"><tbody><tr><td style="border-collapse:collapse;font-family:Arial,sans-serif;font-size:15px;color:#343f44;word-break:break-word;padding:10px 20px"><div id="m_5127046700997499950hs_cos_wrapper_primary_rich_text_field" style="color:inherit;font-size:inherit;line-height:inherit"><div id="m_5127046700997499950hs_cos_wrapper_primary_rich_text_field_" style="color:inherit;font-size:inherit;line-height:inherit"><p style="line-height:175%">Dear priya,<br><br></p><p style="line-height:175%">Kobiton was founded on the idea to make mobile testing accessible to teams of all sizes, without restriction to physical location or geography. We believe that the ability for teams to seamlessly work from anywhere is paramount and is now more important than ever. Organizations the world over are quickly adapting to the “new normal” as they attempt to minimize disruption caused by a sudden need to support “at-home” testers without compromising quality or efficiency. Kobiton lets your remote testing team access physical devices in the cloud, with centralized logging and administration, so that your release cycles can continue as planned, unhindered and uninterrupted.</p><p style="line-height:175%"><br><strong>What we’re doing to help</strong>: Our commitment to the testing community is as strong as ever and we stand ready to help organizations most in need. To that end, if you find that your company is negatively impacted by not having access to devices, we’re offering you and your team:</p><ul style="line-height:175%"><li><p style="line-height:175%">Local device slots to connect your existing on-premises devices, completely free of charge, for 90 days.</p></li><li><p style="line-height:175%">An unlimited number of users to access your local devices worldwide</p></li><li><p style="line-height:175%">No cost, No contract, No catch</p></li></ul><p style="line-height:175%">We know business operations are undergoing fundamental change and we hope this helps make things a little easier.</p></div></div></td></tr></tbody></table><table cellpadding="0" cellspacing="0" width="100%" style="border-spacing:0!important;border-collapse:collapse"><tbody><tr><td style="border-collapse:collapse;font-family:Arial,sans-serif;font-size:15px;color:#343f44;word-break:break-word;padding:10px 20px"><div id="m_5127046700997499950hs_cos_wrapper_module_15850680259271" style="color:inherit;font-size:inherit;line-height:inherit">  <table width="100%" border="0" cellspacing="0" cellpadding="0" style="border-spacing:0!important;border-collapse:collapse">  <tbody><tr>    <td align="center" width="auto" style="border-collapse:collapse;font-family:Arial,sans-serif;font-size:15px;color:#343f44;word-break:break-word;width:auto;display:block">      <table border="0" cellspacing="0" cellpadding="0" style="border-spacing:0!important;border-collapse:collapse">        <tbody><tr>                    <td align="center" style="border-collapse:collapse;font-family:Arial,sans-serif;font-size:15px;color:#343f44;word-break:break-word">          <table style="border-spacing:0!important;background-color:#5c067b;border-radius:5px;border-collapse:separate!important" bgcolor="#5C067B">            <tbody><tr>                          <td align="center" style="border-collapse:collapse;font-family:Arial,sans-serif;font-size:15px;color:#343f44;word-break:break-word">                <a href="https://info.kobiton.com/e2t/c/*W3JnxRS5nyNFrW5V7M0P9knppg0/*W7J9f7Q84hNkBW1mzJqf50jMGb0/5/f18dQhb0Sq5G6BHnX-W6JXRKS2qwv15N32hm9NK3MTXMf5dRdXD6prW7cmS1s5CR6MXW4vpnj15C9pvkW4vgKM198KYmkW53bjnn83GltqW7NM5DD7JtTqnW8mnw907bjnYCW81lBVq9dlBzpW1h4CGY6W4twBW2zjWPK9dSlS6W35rgCl94-4T0N7sLbG-FCG-jW5rC5Q63l6ccrW8mQMWv5SW6pCW6WNpY27R0x14N33FK-yqPkxDVnjZC81H5Z09W7nWk645MXjhDW4c9D2P75n7vQW9gp9yW7twBqmW1hFxf42S3wlmW2Pm4hW5p_SqyW6XXX5j7twVywW55kY8d3qc9bPW3qcNGJ7rHcC7W1zzT_64QrTGsW7Lq1f14BW9QfW2tb0m-1FW3plW2GDvnd57yks_W7p8CC42G-g0QN8_0qlwdh2WLW7K_fYP4YmRL-MfTlLH1KsX1W1K3HSd7v3SSPW5Zg9087K2DmdW1h7XLz5gHkSBW1dB_zp7zKRbpW8mKMqm5MfwfdW2WD86x83K0d_W85Zz8S91yqxKW1_89ht2nTCzyW4Q-5SV4HzlXBf2QhRtv11" style="padding:12px 18px;font-size:16px;font-family:Helvetica,Arial,sans-serif;color:#ffffff;font-weight:normal;text-decoration:none;font-style:normal;display:block;text-align:center" align="center" target="_blank">LEARN MORE</a>              </td>            </tr>          </tbody></table>                    </td>        </tr>      </tbody></table>    </td>  </tr></tbody></table></div></td></tr></tbody></table><table cellpadding="0" cellspacing="0" width="100%" style="border-spacing:0!important;border-collapse:collapse"><tbody><tr><td style="border-collapse:collapse;font-family:Arial,sans-serif;font-size:15px;color:#343f44;word-break:break-word;padding:10px 20px"><div id="m_5127046700997499950hs_cos_wrapper_module_15850680323032" style="color:inherit;font-size:inherit;line-height:inherit"><div id="m_5127046700997499950hs_cos_wrapper_module_15850680323032_" style="color:inherit;font-size:inherit;line-height:inherit"><p style="line-height:175%">Sincerely,</p><p style="line-height:175%"> </p><p style="line-height:175%">Kevin Lee</p><p style="line-height:175%">Kobiton CEO</p></div></div></td></tr></tbody></table></div>        </div>     </div>  <div id="m_5127046700997499950builtin_section-1" class="m_5127046700997499950hse-section m_5127046700997499950hse-section-1-col" style="padding-left:10px;padding-right:10px;padding-bottom:20px">                  <div class="m_5127046700997499950hse-column-container" style="min-width:280px;max-width:600px;width:100%;Margin-left:auto;Margin-right:auto;border-collapse:collapse;border-spacing:0">                <div id="m_5127046700997499950builtin_column_1-0" class="m_5127046700997499950hse-column">  <table cellpadding="0" cellspacing="0" width="100%" style="border-spacing:0!important;border-collapse:collapse"><tbody><tr><td style="border-collapse:collapse;font-family:Arial,sans-serif;font-size:15px;color:#343f44;word-break:break-word;padding:10px 20px"><div id="m_5127046700997499950hs_cos_wrapper_footer_module" style="color:inherit;font-size:inherit;line-height:inherit">              <table width="100%" cellpadding="0" cellspacing="0" style="border-spacing:0!important;border-collapse:collapse;text-align:center;font-family:Arial,sans-serif;font-size:12px;line-height:135%;color:#23496d;margin-bottom:0;padding:0" align="center">    <tbody>        <tr>            <td align="center" valign="top" style="border-collapse:collapse;font-family:Arial,sans-serif;font-size:15px;color:#343f44;word-break:break-word;text-align:center;margin-bottom:0;line-height:135%;padding:10px 20px">                <p style="font-family:Arial,sans-serif;font-size:12px;font-weight:normal;text-decoration:none;font-style:normal;color:#23496d">                  Kobiton, 1776 Peachtree Street NW, Suite 200N, Atlanta, Georgia 30309, United States, (678) 235-4095                </p>                <p>                                    <a href="https://info.kobiton.com/hs/manage-preferences/unsubscribe-all?d=Vnh1vf90sf_WV-90hL4rvFwsW4hJ2C53_R5YFW22_pF_3zbV8YW3Fbt5q87g-JHN1fkvKFkjgfCW8vR0bb895NK0W5-Fc6r6pddy7W880hXw4LH2GqW1HWGWn7jDJDWN89b4p67RQTCVkw-8B1vlcCbf229Ckm04&amp;v=3&amp;utm_campaign=Remote%20Hands&amp;utm_source=hs_email&amp;utm_medium=email&amp;utm_content=85192493&amp;_hsenc=p2ANqtz-9z-0wxX5CbgSmYRRW4IiNC0p6SqsYtli5cCT5ivacN3MKS4x6SW5srd1DDxeEDCawcuRxGFISMZwg3YUMZAcTmenEuPqxbh1AZx4JmeAHgJfEOoOk&amp;_hsmi=85192493" style="font-family:Helvetica,Arial,sans-serif;font-size:12px;color:#5c067b;font-weight:normal;text-decoration:underline;font-style:normal" target="_blank">Unsubscribe</a>                                    <a href="https://info.kobiton.com/hs/manage-preferences/unsubscribe?d=Vnh1vf90sf_WV-90hL4rvFwsW4hJ2C53_R5YFW22_pF_3zbV8YW3Fbt5q87g-JHN1fkvKFkjgfCW8vR0bb895NK0W5-Fc6r6pddy7W880hXw4LH2GqW1HWGWn7jDJDWN89b4p67RQTCVkw-8B1vlcCbf229Ckm04&amp;v=3&amp;utm_campaign=Remote%20Hands&amp;utm_source=hs_email&amp;utm_medium=email&amp;utm_content=85192493&amp;_hsenc=p2ANqtz-9z-0wxX5CbgSmYRRW4IiNC0p6SqsYtli5cCT5ivacN3MKS4x6SW5srd1DDxeEDCawcuRxGFISMZwg3YUMZAcTmenEuPqxbh1AZx4JmeAHgJfEOoOk&amp;_hsmi=85192493" style="font-family:Helvetica,Arial,sans-serif;font-size:12px;color:#5c067b;font-weight:normal;text-decoration:underline;font-style:normal" target="_blank">Manage preferences</a>                                  </p>            </td>        </tr>    </tbody></table></div></td></tr></tbody></table></div>        </div>     </div></div>          </td>        </tr>      </tbody></table>    </div>  <img src="https://info.kobiton.com/e2t/o/*N67V4_GknqSnW32Nn-j7cCzl20/*W7Krp5W4Sxbf8W3fTmyf4w7ylP0/5/f18dQhb0S6Hh5gqzRJW3k-SSF5VQHvDW6bJD1B51BQRPW55f0yJ5QT8DBW4Pw4J13DlgFjVqT_Cy2-CV4TW3B_r1n4kFlYgW5kcPwX4tzCglW5bWW8g1Js3pbW2cyH2G5kCKMKW4gNTvh2kjf4HW47ykvV4jzPxnW86RpGF80ymNmD8mBp-QGtlf3H6MGg03" alt="" width="1" height="1" border="0" style="display:none!important;min-height:1px!important;width:1px!important;border-width:0!important;margin-top:0!important;margin-bottom:0!important;margin-right:0!important;margin-left:0!important;padding-top:0!important;padding-bottom:0!important;padding-right:0!important;padding-left:0!important"></div></div></div>`;

export default class Example extends Component {
  render() {
    return (
      <ScrollView style={{ flexGrow: 1, backgroundColor: '#00ff00' }}>
         <AutoHeightWebView
          scrollEnabled={false}
          allowFileAccess={true}
          dataDetectorTypes="all"
          mixedContentMode="always"
          originWhitelist={['*']}
          source={{ html: `${htmlContent}` }}
          scalesPageToFit={true}
          cacheEnabled={false}
          onShouldStartLoadWithRequest={event => {
            if (event.url) {
              Linking.canOpenURL(event.url).then(supported => {
                if (supported) {
                  Linking.openURL(event.url);
                }
              });
              return false;
            } else {
              return true;
            }
          }}
          style={{ width: Dimensions.get('window').width - 15}}
        />
      </ScrollView>
    );
  }
}

**Expected behavior:**
Infinite scroll issue should not be observed

**Screenshots/Videos:**

**Environment:**
 - OS: Android
 - OS version: 10
 - react-native version: 0.63.2
 - react-native-webview version:10.9.0
 - react-native-autoheight-webview version:1.5.4

**Comment by msuma268** [comment]
Same issue is observed with the below html too:

const autoHeightHtml0 = `<div dir="ltr"><br><br><div class="gmail_quote"><br><br><u></u>                                                                        <div bgcolor="#ffffff" style="margin:0!important;padding:0!important;font-family:Arial,sans-serif;font-size:15px;color:#343f44;word-break:break-word">        <div style="background-color:#ffffff" bgcolor="#ffffff">      

<table cellpadding="0" cellspacing="0" style="border-spacing:0!important;border-collapse:collapse;margin:0;padding:0;width:100%!important;min-width:320px!important;!important" width="100%" **height="100%"**> 
  <tr>
    <td>
      <p>This is a paragraph</p>
      <p>This is another paragraph</p>
    </td>
    <td> <p>This is a paragraph</p>
    </td>
  </tr>
  <tr>
    <td>This cell contains a list
      <ul>
        <li>apples</li>
        <li>bananas</li>
        <li>pineapples</li>
      </ul>
    </td>
    <td>HELLO</td>
  </tr>
</table>
</div> </div></div></div>`;     

However, **if i remove the height="100%" property from <table>** then the infinite scroll issue is not observed. That holds true for the sample email that I posted earlier as well.

Also if I add <table> within simple html and set height as "100%", issue is not seen. This seems to be happening only when it is enclosed within <div>.

@iou90 Any help or pointers to resolve this issue will be greatly appreciated.

**Comment by iou90** [comment]
``` javascript
<br />
<div style="height: 100%; background-color: red;" />
```
The problem is not related to "table" or "height: 100%", but to that the actual height is larger than the height of webview.
There is resizing infinitely because the height of Br + Div (height 100%) is always larger than its container's.
