### ISSUE TITLE
fullscreen button is disabled on android. though works fine on ios

### ISSUE THREAD

**Issue by krunalbad** [iou90/react-native-autoheight-webview#185]
**Bug description:**
fullscreen button is disabled on android. though works fine on ios 

**To Reproduce:**
Add the source code provided below in `html` prop to reproduce

**Source (static HTML or url):**
`<iframe title="Office Hours: Mastering components" width="500" height="281" src="https://www.youtube.com/embed/fNQRXierLhQ?feature=oembed" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>`

**Expected behavior:**
Full screen should work

**Screenshots/Videos:**
![Screenshot 2020-10-07 at 3 05 16 PM](https://user-images.githubusercontent.com/45413622/95314388-dd982700-08ae-11eb-8c87-3b3f9b1d5f08.png)

**Environment:**
 - OS: Android Q
 - OS version: 10 
 - react-native version: 0.63.2
 - react-native-webview version: 9.4.0
 - react-native-autoheight-webview version: 1.5.1

**Comment by iou90** [comment]
``` javascript
allowsFullscreenVideo={true}
```
Try this.

**Comment by krunalbad** [comment]
I did that already but it didn't worked. Then I used another workaround. Closing this issue

**Comment by DoctorRyner** [comment]
> I did that already but it didn't worked. Then I used another workaround. Closing this issue

What is this "another" workaround?

**Comment by n0umankhan** [comment]
@krunalbad which workaround can you please help

**Comment by ToStefan** [comment]
@DoctorRyner what is workaround i have same situtation when  allowsFullscreenVideo={true} does not help. ???

**Comment by krunalbad** [comment]
@n0umankhan @ToStefan I have used this` import { WebView } from 'react-native-webview';` which resolved my issues for YouTube embed
