### ISSUE TITLE
1.5.5 typescript require some props.

### ISSUE THREAD

**Issue by jihokim2** [iou90/react-native-autoheight-webview#186]
**Bug description:**
1.5.5 index.d.ts required onSizeUpdated, files, style, customScript, customStyle, viewportContent, scalesPageToFit, scrollEnabledWithZoomedin
**To Reproduce:**
use typescript
**Source (static HTML or url):**
<AutoHeightWebView
          source={{uri: https://tas-ups.taleo.net/careersection/jobdetail.ftl?job=064485&lang=en}}
          style={{width: Dimensions.get('window').width - 40}}
          scrollEnabled={false}
          viewportContent={'width=device-width, user-scalable=no'}
          scrollEnabledWithZoomedin={false}
          onLoadStart={() => setLoading(true)}
          allowFileAccess={true}
          scalesPageToFit={true}
          onMessage={onSecondViewMessage}
          originWhitelist={['*', 'https://*', 'http://*']}
          onShouldStartLoadWithRequest={() => true}
          mixedContentMode="compatibility"/>
      )}
**Expected behavior:**
. If some props are missed, It should not make typescript error.
**Screenshots/Videos:**

**Environment:**
 - OS: MAC
 - OS version:
 - react-native version: 0.63.3
 - react-native-webview version:10.10.2
 - react-native-autoheight-webview version: 1.5.5

**Comment by iou90** [comment]
Should be fixed with 1.5.7.

**Comment by jihokim2** [comment]
At 1.5.7 I checked issue was cleared. Thank you.
