### ISSUE TITLE
Scroll Inside a tab navigator with gestures

### ISSUE THREAD

**Issue by praneeth-hiver** [iou90/react-native-autoheight-webview#188]
**Bug description:**
I have a webview inside a [createBottomTabNavigator v4](https://reactnavigation.org/docs/4.x/bottom-tab-navigator) with swipe gesture between tabs enabled and when I scroll horizontally the tab's swipe kicks in and the scroll doesn't happen even with scrollEnabled

**To Reproduce:**
specific to android

**Expected behavior:**
Expected it to trigger the swipe gesture after the ah-webview scroll has been done.

**Screenshots/Videos:**
![ezgif-6-28cdb317b774](https://user-images.githubusercontent.com/59868493/100927887-8065ce00-350b-11eb-97e5-9fdca4daa181.gif)

**Environment:**
 - OS: Android
 - OS version: Android 10
 - react-native version: 0.60.5
 - react-native-webview version: 10.8.3
 - react-native-autoheight-webview version: 1.5.7

**Comment by praneeth-hiver** [comment]
Hey @iou90 any updated on this?

**Comment by iou90** [comment]
``` javascript
viewportContent={'width=device-width, user-scalable=no'}
```
Does this work?

**Comment by praneeth-hiver** [comment]
Tried adding viewportContent, it didn't work. @iou90 
Anyway to get onScroll event for start and end of webview horizontal scroll if viewportContent's width is > device width?

**Comment by iou90** [comment]
@praneeth-hiver 
postMessage within customScript & onMessage
