### ISSUE TITLE
a bug

### ISSUE THREAD

**Issue by mmorcc** [iou90/react-native-autoheight-webview#189]
error: bundling failed: Error: Unable to resolve module `./momoize` from `E:\wor
kspace\web\heatsys\hs\heatingsystem\heating-mobile\spongeMobile\node_modules\rea
ct-native-autoheight-webview\autoHeightWebView\index.js`: The module `./momoize`
 could not be found from `E:\workspace\web\heatsys\hs\heatingsystem\heating-mobi
le\spongeMobile\node_modules\react-native-autoheight-webview\autoHeightWebView\i
ndex.js`. Indeed, none of these files exist:
  * `E:\workspace\web\heatsys\hs\heatingsystem\heating-mobile\spongeMobile\node_
modules\react-native-autoheight-webview\autoHeightWebView\momoize(.native||.andr
oid.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.t
s|.android.tsx|.native.tsx|.tsx)`
  * `E:\workspace\web\heatsys\hs\heatingsystem\heating-mobile\spongeMobile\node_
modules\react-native-autoheight-webview\autoHeightWebView\momoize\index(.native|
|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native
.ts|.ts|.android.tsx|.native.tsx|.tsx)`
    at ModuleResolver.resolveDependency (E:\workspace\web\heatsys\hs\heatingsyst
em\heating-mobile\spongeMobile\node_modules\metro\src\node-haste\DependencyGraph
\ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (E:\workspace\web\heatsys\hs\heatings
ystem\heating-mobile\spongeMobile\node_modules\metro\src\node-haste\DependencyGr
aph\ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (E:\workspace\web\heatsys\hs\heatingsys
tem\heating-mobile\spongeMobile\node_modules\metro\src\node-haste\DependencyGrap
h.js:283:16)
    at Object.resolve (E:\workspace\web\heatsys\hs\heatingsystem\heating-mobile\
spongeMobile\node_modules\metro\src\lib\transformHelpers.js:261:42)
    at dependencies.map.result (E:\workspace\web\heatsys\hs\heatingsystem\heatin
g-mobile\spongeMobile\node_modules\metro\src\DeltaBundler\traverseDependencies.j
s:399:31)
    at Array.map (<anonymous>)
    at resolveDependencies (E:\workspace\web\heatsys\hs\heatingsystem\heating-mo
bile\spongeMobile\node_modules\metro\src\DeltaBundler\traverseDependencies.js:39
6:18)
    at E:\workspace\web\heatsys\hs\heatingsystem\heating-mobile\spongeMobile\nod
e_modules\metro\src\DeltaBundler\traverseDependencies.js:269:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (E:\workspace\web\heatsys\hs\heatingsystem\heating-mob
ile\spongeMobile\node_modules\metro\src\DeltaBundler\traverseDependencies.js:87:
24)

    "react": "16.8.3",
    "react-native": "0.59.5",
    "react-native-autoheight-webview": "^1.5.2",
    "react-native-webview": "^11.0.2"

**Comment by iou90** [comment]
Sorry but fixes and new features will only be included in the last version.

**Comment by mmorcc** [comment]
i use flex:1 fix it
