### ISSUE TITLE
customScript is not working for meta in android

### ISSUE THREAD

**Issue by sumanmyon** [iou90/react-native-autoheight-webview#190]
let width = Dimensions.get('window').width - 50
 let script = `const meta = document.createElement('meta'); 
                    meta.setAttribute('content', 'width=device-width, initial-scale=0.5, maximum-scale=0.5, user-scalable=0, shrink-to-fit=no');
                    meta.setAttribute('name', 'viewport'); 
                    document.getElementsByTagName('head')[0].appendChild(meta); `  

 <AutoHeightWebView
        style={{ width: width}}
        script={script}
        heightOffset={5}
        onSizeUpdated={size => {console.log("height= "+size.height); }}
        files={[{
            href: 'cssfileaddress',
            type: 'text/css',
            rel: 'stylesheet'
        }]}
        javaScriptEnabled={true}
        scalesPageToFit={Platform.OS === 'Android' ? true : false}
        source={{ html:`${message.trim()}` }}
        viewportContent={`width=device-width, user-scalable=no, initial-scale=0.75`}
    />

**Comment by iou90** [comment]
Setting viewportContent instead of creating meta tag with customScript.
