### ISSUE TITLE
when you use navigation.navigate the app crash on android using webview because androidHardwareAccelerationDisabled

### ISSUE THREAD

**Issue by webuijorgeGL** [iou90/react-native-autoheight-webview#191]
**Bug description:**

when you use navigation.navigate the app crash on android using webview because androidHardwareAccelerationDisabled

**To Reproduce:**

**Source (static HTML or url):**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS:
 - OS version:
 - react-native version:
 - react-native-webview version:
 - react-native-autoheight-webview version:

**Comment by iou90** [comment]
Please provide your environment.

**Comment by webuijorgeGL** [comment]
DEV and Production 
Android 9

**Comment by zaka5192** [comment]
This might help
https://github.com/react-native-webview/react-native-webview/issues/429#issuecomment-474114522

**Comment by gingerJY** [comment]
<AutoHeightWebView style={{ opacity: 0.99, minHeight: 1 }} .... />
add opacity and minHeight

**Comment by DerekNien** [comment]
React Native Navigation with Stack animationEnabled will cause this problem.
This might help:
https://github.com/facebook/react-native/issues/25494#issuecomment-724871241
