### ISSUE TITLE
Be accessible 

### ISSUE THREAD

**Issue by webuijorgeGL** [iou90/react-native-autoheight-webview#192]
**Is your feature request related to a problem? If so, Please describe.**

Is not a problem

**Describe the solutions you came up with**

The dependency could be accessible to different readers with rules of https://reactnative.dev/docs/accessibility#accessibilityrole

**Platform targeting (iOS/Android)**

Both

**Additional context**

**Comment by iou90** [comment]
Be accessible is a good idea but I think maybe is more related to react-native-webview?
