### ISSUE TITLE
TypeError (2604)

### ISSUE THREAD

**Issue by andordavoti** [iou90/react-native-autoheight-webview#194]
Getting this TypeError:
JSX element type 'AutoHeightWebView' does not have any construct or call signatures.ts(2604)

 - OS: MacOS
 - OS version: 11.2
 - react-native version: 0.63
 - react-native-webview version: 10.7.0
 - react-native-autoheight-webview version: 1.5.7

**Comment by iou90** [comment]
``` json
"peerDependencies": {
    "react": ">= 16.8.0",
    "react-native": ">= 0.60.0",
    "react-native-webview": ">= 10.9.0"
  }
```

Please using correct version os dependencies.
