### ISSUE TITLE
Support setSupportMultipleWindows

### ISSUE THREAD

**Issue by conradchenghk01** [iou90/react-native-autoheight-webview#196]
Since react-native-webview v11 will turn setSupportMultipleWindows from false to true

If downstream update to [v11](https://github.com/react-native-webview/react-native-webview/releases/tag/v11.0.0), the behavior for autoHeight-webview will be change together, so it is better to add a props or pinned react-native-webview under <=10 to avoid behavior change.

**Comment by iou90** [comment]
You can set it to false manually.

**Comment by conradchenghk01** [comment]
> You can set it to false manually.

It's work, thank you.
