### ISSUE TITLE
Allow loading local HTML files without prop type warning

### ISSUE THREAD

**Issue by laila-vinson** [iou90/react-native-autoheight-webview#197]
When loading HTML directly from source, the web view appears to work on iOS, but we get the following warning:

`Warning: Failed prop type: Invalid prop `source` of type `number` supplied to `ForwardRef`, expected `object`.`

Sample code:

```
import AutoHeightWebView from "react-native-autoheight-webview";
const HTMLFile = require("./my-asset-folder/local-site.html");

function MyComponent() {
 {
    return (
      <AutoHeightWebView source={HTMLFile} />
    );
  }
}
```

However, the web view seems to load fine despite the warning, and glancing at the code it seems to simply pass the source to the internal WebView. This is on iOS. Is this expected or should the "source" also accept a "number" propType? (Not sure if this is a bug report or feature request)

**Comment by iou90** [comment]
The ```source``` type: https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#source

**Comment by laila-vinson** [comment]
Oh I see, so loading via "require" is not documented for react-native-webview. Should have checked there first. Thanks!
