### ISSUE TITLE
Sometimes WebView capture the scroll

### ISSUE THREAD

**Issue by VicoErv** [iou90/react-native-autoheight-webview#198]
**Bug description:**
I have autoheightwebview inside scrollview, and sometimes it capture the scroll event. And eventually the scroll is trapped inside autoheightwebview unless I tap outside it.

**To Reproduce:**
Create react native project and install AutoHeightWebView then run it on iOs

**Expected behavior:**
Scroll gesture should've disabled

**Screenshots/Videos:**

**Environment:**
 - OS: iOs
 - OS version: 14.4
 - react-native version: 0.63.4
 - react-native-webview version: 11.3.2
 - react-native-autoheight-webview version: 1.5.8

**Comment by VicoErv** [comment]
Or maybe this is a fix? [Disable WebView's Vertical Scrolling in React Native
](https://stackoverflow.com/questions/52100810/disable-webviews-vertical-scrolling-in-react-native)

`scrollEnabled={false}`

**Comment by shivam0831** [comment]
how to fix this in android? `scrollEnabled={false}` works only in ios.

**Comment by ahaverty** [comment]
@shivam0831 did you find a fix for android?
