### ISSUE TITLE
Cannot read property 'Commands' of undefined on line 92

### ISSUE THREAD

**Issue by dima11221122** [iou90/react-native-autoheight-webview#2]
My code:
`import WebView from 'react-native-autoheight-webview';`
`<WebView html={html_code} />`
I got error:
`Cannot read property 'Commands'`
`AutoHeightWebView.postMessage`
`index.android.js:92`
Versions of packages:
- react@15.4.2
- react-native@0.41.2
- react-native-autoheight-webview@0.1.0

**Comment by dima11221122** [comment]
Android 6.0

**Comment by iou90** [comment]
I can not replicate this issue with 
react@15.4.2
react-native@0.41.2
react-native-autoheight-webview@0.1.0
android api23 (6.0)

**Comment by iou90** [comment]
Linking this package may fixed the issue: react-native link react-native-autoheight-webview
