### ISSUE TITLE
webview自带的onMessage属性以及一些其它的属性没有

### ISSUE THREAD

**Issue by xiangming25** [iou90/react-native-autoheight-webview#21]
有一个需求，需要对webview中的图片进行点击监听，点击图片后查看大图。
想用webview 的 onMessage以及一些其它属性实现，其它的属性没有提供props。

**Comment by iou90** [comment]
AutoheightWebView does not implement all rn WebView features (https://github.com/facebook/react-native/blob/master/Libraries/Components/WebView/WebView.android.js) and I think it's not related to the auto height feature.

**Comment by Tomatoo** [comment]
same question.

why not implement rn webview features？

if i use 'react-native-autoheight-webview', i cannot use onMessage and other props?
