### ISSUE TITLE
Import react-native component in the source ---> html of the webview

### ISSUE THREAD

**Issue by petkovv** [iou90/react-native-autoheight-webview#210]
Hey guys, I couldn't find any solution or workaround for my issue so I decided to ask my question here. So I need to do something which may seem pretty strange but there is no other way (at least I couldn't find) to solve this issue. I was wondering if there is any way in the source ---> html of the webview somewhere to import react-native component. Something like this should happen:

```
<div>
   <p>some text</p>
   <ReactNativeComponent someProps={someProp} someOtherProp={someOtherProp} />
   <p>some text</p>
</div>
```

I wonder if it is possible or if not I will be happy to see any suggestions for workarounds for my case. Thanks in advance :)

**Comment by RayKay91** [comment]
render two WebViews one below and one above the react native component and inject css styling to make the styles match

**Comment by iou90** [comment]
I think it's not related to this lib (for auto height/width webview).
