### ISSUE TITLE
App keep stopping when try to navigate back with React Navigation 6 

### ISSUE THREAD

**Issue by iamkevinhuang** [iou90/react-native-autoheight-webview#213]
**Bug description:** When I used the AutoHeightWebView component, the screen was render the component with no issue, but when I tried to go back with React Navigation 6 back button in Screen Header the app was keep stopping. When I comment the AutoHeightWebView, I can go back to previous screen without any issue.

**To Reproduce:** 
```
const RegisterLogDetail = ({when, comment, by, statusCaption}) => {
  return (
    <View style={styles.container}>
      <BaseText variant="bodyBold">{when}</BaseText>
      <BaseText variant="body">{statusCaption}</BaseText>
      <SpacerComponent size="medium" />
      <Divider style={styles.divider} />
      <SpacerComponent size="medium" />
      <BaseText variant="bodySemibold">{by} : </BaseText>
      <AutoHeightWebView
        customStyle={`body, html{
          overflow-x: hidden;
        }`}
        source={{
          html: '<p>Test</p>',
        }}
      />
    </View>
  );
};

```
**Source (static HTML or url):**
`<p>Test</p>`

**Expected behavior:**
Can Go Back to before screen with no Issue 
**Screenshots/Videos:**
Video : https://1drv.ms/v/s!AjCPaLSI-ghXoWeCZWHWkEmYj8aM?e=2PCfJz

**Environment:**
 - OS: Android
 - OS version: 10
 - react-native version: 0.66.0
 - react-native-webview version: 11.14.0
 - react-native-autoheight-webview version: 1.5.8

**Comment by Poheart** [comment]
I also had a similar issue with the app crashing when I try to navigate back with Android devices, 

Try adding `style={{ height: Dimensions.get('window').height }}` to  `<AutoHeightWebView>`

You can also try to add `androidHardwareAccelerationDisabled={true}` to see if it works.

**Comment by iou90** [comment]
@iamkevinhuang Can you provide a minimum reproduction repo?
