### ISSUE TITLE
Crash with Android 12

### ISSUE THREAD

**Issue by sylv1b** [iou90/react-native-autoheight-webview#219]
When navigating to a screen containing this component, the app crashes without warning in the console. When waiting to render this component using setTimeout helps sometimes, but this is very random. 
it works normally with earlier versions of Android and IOS.

**Comment by qzlu-cyber** [comment]
I had the same problem, in fact it also crashes on the pixel emulator on android 11

**Comment by IgarMikhailov** [comment]
Set the style of <AutoHeightWebView  style={{ width: Dimensions.get('window').width - 15, marginTop: 35, opacity: 0.99 }} />

**Comment by iou90** [comment]
Bug description:
To Reproduce:
Source (static HTML or url):
Expected behavior:
Environment:
OS: Android
OS version:
react-native version:
react-native-webview version:
react-native-autoheight-webview version:

Please provide more information and if the demo works (react native: 0.69.1, react native webview: 11.22.7, Android 12). @sylv1b @qzlu-cyber

**Comment by ddikodroid** [comment]
> When navigating to a screen containing this component, the app crashes without warning in the console. When waiting to render this component using setTimeout helps sometimes, but this is very random. it works normally with earlier versions of Android and IOS.

did you managed to solve it?

**Comment by sylv1b** [comment]
> > When navigating to a screen containing this component, the app crashes without warning in the console. When waiting to render this component using setTimeout helps sometimes, but this is very random. it works normally with earlier versions of Android and IOS.
> 
> did you managed to solve it?

Yes, I found a workaround. I works if you set the opacity to 0.99 like this:

`style={{ opacity: 0.99 }}`

**Comment by zd1471278687** [comment]
> 

It's will have some ui problem on vivo or oppo device
add overScrollMode={'never'} property on ScrollView can resolve this problem

**Comment by iou90** [comment]
https://github.com/react-native-webview/react-native-webview/issues/1915
It seems not related to this lib.
