### ISSUE TITLE
ERROR    Invariant Violation: requireNativeComponent: "RNCWebView" was not found in the UIManager.

### ISSUE THREAD

**Issue by donghuiqiu** [iou90/react-native-autoheight-webview#220]
**Bug description:** could not run project after run yarn add react-native-autoheight-webview react-native-webview ,and show this

**To Reproduce:**

**Source (static HTML or url):**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS:android
 - OS version:android 10
 - react-native version:0.63.3
 - react-native-webview version:11.18.0
 - react-native-autoheight-webview version:1.5.2

**Comment by iou90** [comment]
I think it's not related to this lib (react-native-webview related https://stackoverflow.com/questions/61832232/invariant-violation-requirenativecomponent-rncwebview-was-not-found-in-the-u)
