### ISSUE TITLE
deprecatedReactNativePropTypes.default.shape is not a function

### ISSUE THREAD

**Issue by MykhailoButkevych-PE** [iou90/react-native-autoheight-webview#234]
Issue appeared after: https://github.com/iou90/react-native-autoheight-webview/issues/228
Thanks https://github.com/mauricekleine - he already mentioned it in a comment: https://github.com/iou90/react-native-autoheight-webview/issues/228#issuecomment-1187094355
I'm just creating a new issue, so it'll be more visible.

`Downgrading to 1.6.1 helps`

**Comment by stevekuznetsov** [comment]
Oops, sorry all - I think https://github.com/iou90/react-native-autoheight-webview/pull/235 fixes it, but would appreciate a check!

**Comment by tranminhnhat1005** [comment]
PropTypes.shape is not supported in deprecated-react-native-prop-types in node_modules/react-native-autoheight-webview/autoHeightWebView/index.js

My project info: 
"react": "16.8.6",
"react-native": "0.60.5", 
"react-native-autoheight-webview": "1.5.8" 

was good with PropTypes from prop-types

**Comment by iou90** [comment]
It should be fixed on v1.6.3. (https://github.com/iou90/react-native-autoheight-webview/releases/tag/v1.6.3)
