### ISSUE TITLE
Destroy is not a function

### ISSUE THREAD

**Issue by Alyka3000** [iou90/react-native-autoheight-webview#237]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-autoheight-webview@1.6.3` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-autoheight-webview/autoHeightWebView/index.js b/node_modules/react-native-autoheight-webview/autoHeightWebView/index.js
index 23e5dea..48a59a2 100644
--- a/node_modules/react-native-autoheight-webview/autoHeightWebView/index.js
+++ b/node_modules/react-native-autoheight-webview/autoHeightWebView/index.js
@@ -65,13 +65,12 @@ const AutoHeightWebView = React.memo(
     const {currentSource, script} = reduceData(props);
 
     const {width, height} = size;
-    useEffect(
-      () =>
+    useEffect(() => {
         onSizeUpdated &&
         onSizeUpdated({
           height,
           width,
-        }),
+        })},
       [width, height, onSizeUpdated],
     );
 
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by iou90** [comment]
It should be fixed on v1.6.4. (https://github.com/iou90/react-native-autoheight-webview/releases/tag/v1.6.4)
