### ISSUE TITLE
Add possibility of passing height via props

### ISSUE THREAD

**Issue by andreysaleba** [iou90/react-native-autoheight-webview#24]
Thanks for the library, it's great.

But in my project I have a case when I need to pass custom height to the webview to display only a preview of it, and when the button is pressed I render it in auto height, something like 'Read More' functionality.

So I'm missing the possibility of passing custom height to webview via props here.

I can add it with PR if you are interested in it.

**Comment by iou90** [comment]
It sounds nice (but may cause some issues as well ?), anyway, welcome your PR =v=
