### ISSUE TITLE
Scrolling on android jumps down to the top of the webview after the webview height has increased

### ISSUE THREAD

**Issue by ahaverty** [iou90/react-native-autoheight-webview#240]
**Bug description:**
Scrolling on android jumps down to the top of the webview, after the webpage's height is increased (e.g via an expanded accordion in the webview)

**To Reproduce:**
With a webview of a webpage, containing expandable accordion views.
Expand one of the accordion's in the webview, and attempt to scroll to the top of the react native scrollview page.

**Expected behavior:**
Expect the page to scroll back to the top without shooting back down.
Notably, this works well on iOS.

**Screenshots/Videos:**
First 10 seconds showing scroll works as expected initially.
Last 15 seconds showing how scroll jumps down the page after the accordion in the webview was expanded. Effectively preventing a user from scrolling back to the top of the outer scrollview.

https://user-images.githubusercontent.com/2920947/185146343-34087761-20fa-412f-a3c9-36bf613492e0.mp4

**Environment:**
 - OS: Android 
 - OS version: v13
 - react-native version: 0.68.1
 - react-native-webview version: 11.23.0
 - react-native-autoheight-webview version: 1.64

**Comment by iou90** [comment]
Please provide a minimal simple html/uri to reproduce this issue.

**Comment by ahaverty** [comment]
Thanks @iou90 , we've since discovered the issue was due to an animated value for adjusting the header padding in our react native view. Removing this, scrolling now works well on both platforms. Thanks for checking in!
