### ISSUE TITLE
scalesPageToFit false  not work on Android 7.0

### ISSUE THREAD

**Issue by donghuiqiu** [iou90/react-native-autoheight-webview#242]
**Bug description:**
scalesPageToFit false  not work on Android 7.0 , still can sacle  page

**To Reproduce:**

two finger to scale

**Source (static HTML or url):**
https://imgurl.ninedvr.com/laitan/book/2022/09/01/090db638-a736-473d-9f9b-cd0e9f3ea84d.html

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS: Android 
 - OS version: Android 7.0
 - react-native version: 0.63.2
 - react-native-webview version: 11.2.1
 - react-native-autoheight-webview version:1.6.1

**Comment by iou90** [comment]
It does not already work on Android 7.0 with react-native-webview, so it's unrelated to this lib.
Maybe this link will help you: https://github.com/react-native-webview/react-native-webview/pull/275

**Comment by donghuiqiu** [comment]
Thanks for your suggest




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "iou90/react-native-autoheight-webview"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月6日(星期二) 中午12:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [iou90/react-native-autoheight-webview] scalesPageToFit false  not work on Android 7.0 (Issue #242)





 
It does not already work on Android 7.0 with react-native-webview, so it's unrelated to this lib.
 Maybe this link will help you: react-native-webview/react-native-webview#275
