### ISSUE TITLE
Cannot read properties of undefined (reading 'getBoudningClientRect')

### ISSUE THREAD

**Issue by ProvidenceXz** [iou90/react-native-autoheight-webview#243]
**Bug description:** Upon rendering the WebView using a `uri` source, an error pops up `Cannot read properties of undefined (reading 'getBoudningClientRect')`

In WebView I'm using server-rendered react with nestJS. Upon examining the code I see that the package is trying to wrap each individual element in a `wrapper` div, but in this case the `wrapper` is undefined. This error only happens few seconds after the WebView has been rendered.

**Environment:**
 - OS: Android
 - OS version: Android 12
 - react-native version: 0.68.2
 - react-native-webview version: 11.23.0
 - react-native-autoheight-webview version: 1.6.4

**Comment by iou90** [comment]
Please provide your uri source.

**Comment by ProvidenceXz** [comment]
> Please provide your uri source.

As of now, it is a local endpoint. Will let you know once it's accessible. But here's what's happening in the uri:

An editor based on lexical (https://playground.lexical.dev/) which uses `ContentEditable` under the hood (https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/contenteditable)

And for when the error would occur on my local:

Trigger height adjustment in WebView (overflow y by inserting new lines) -> type anything (creates a new element)
