### ISSUE TITLE
ios 16 beta, bounces={false} not working

### ISSUE THREAD

**Issue by baesumin** [iou90/react-native-autoheight-webview#244]
**Bug description:**
when using ios 16 beta, bounces={false} doesn't work..
Is there a way to fix it myself? Or should I wait for Apple to fix it...
thanks

**Environment:**
 - OS: ios
 - OS version: 16 beta
 - react-native version: 0.66.0
 - react-native-webview version: 11.14.4
 - react-native-autoheight-webview version: 1.6.1

**Comment by iou90** [comment]
It's unrelated to this lib.
FYI: https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#bounces
