### ISSUE TITLE
All props not sent to webview

### ISSUE THREAD

**Issue by Heidan34** [iou90/react-native-autoheight-webview#26]
Hi, could you pass all webview's default props to the webview ? like "onLoadStart" "onLoadEnd" "onShouldStartLoadWithRequest"...

Thanks in advance

**Comment by iou90** [comment]
For capacity reason, I can not implement all rn WebView properties, to use 0.4.0 for onLoad, onLoadStart, onLoadEnd and onShouldStartLoadWithRequest on iOS.
