### ISSUE TITLE
[Android] onHeightUpdated not triggered

### ISSUE THREAD

**Issue by bltnico** [iou90/react-native-autoheight-webview#3]
Props `onHeightUpdated` is never triggered on Android so my webview height doesn't change !

RN : 0.39.0
react-native-autoheight-webview : 0.1.2
Android : 7.1 (emulator)

**Comment by iou90** [comment]
I can not replicate this issue. You can test it with the new demo code on your environment.

RN : 0.39.0
react-native-autoheight-webview : 0.1.2
Android : 7.1.1 (emulator)
