### ISSUE TITLE
undefined is not an object (evaluating '_reactNative.UIManager.RCTAutoHeightWebView.Commands')

### ISSUE THREAD

**Issue by Ryan007008** [iou90/react-native-autoheight-webview#33]
code:
 <AutoHeightWebView
       source={{ html: this.htmlBody }}
 />

error:
undefined is not an object (evaluating '_reactNative.UIManager.RCTAutoHeightWebView.Commands')

Versions of packages:
react@^0.14.55
react-native@^0.46.0
react-native-autoheight-webview@0.3.1
android@6.0

**Comment by iou90** [comment]
react-native link react-native-autoheight-webview

**Comment by clycheng2015** [comment]
same to me

**Comment by iou90** [comment]
@clycheng2015 Versions of packages ?

**Comment by clycheng2015** [comment]
@iou90  
"react": "^16.0.0",
 "react-native": "^0.50.3",
  error show '...._reactNative.UIManager.RCTAutoHeightWebView not exist',I executed this the link，but this error still exists

**Comment by clycheng2015** [comment]
I have solve the last error as I add dependence by hand but not link ,but now,anthor error is the page is blank,nothing to show,but normal as the origin WebView, do you thnow why?

**Comment by iou90** [comment]
@Ryan007008 @clycheng2015 does the last demo work with you ?
