### ISSUE TITLE
Height doesn't change dynamically

### ISSUE THREAD

**Issue by efkan** [iou90/react-native-autoheight-webview#35]
Hello,

First of all, thanks for this useful module.

But when resizing HTML content, `react-native-autoheight-webview` is not changed.

Changing HTML source code of `react-native-autoheight-webview` causes screen blinking becuase of re-rendering. In contrast, hiding and showing html tags by using javascript is more smooth solution. However, the component doesn't works dynamically.

I wonder that is there any way to re-calculate and return the height value?

**Comment by iou90** [comment]
It is supported only on iOS, what is your platform?

**Comment by efkan** [comment]
The platform was Android. 

I had to use [this code](https://gist.github.com/epeli/10c77c1710dd137a1335) by changing the code a bit.

Supportting to dynamic height would be great I think.

(I use a link to show/hide another HTML tag by using embedded JavaScript code in HTML source)

**Comment by iou90** [comment]
please try @0.10.0
