### ISSUE TITLE
自适应高度计算不准确，显示不全

### ISSUE THREAD

**Issue by yangslgithub** [iou90/react-native-autoheight-webview#38]
v 0.3.1
rn version 0.45.1

**Comment by calvinkei** [comment]
check if this PR solves your problem?
https://github.com/iou90/react-native-autoheight-webview/pull/40

**Comment by gzLonglilin** [comment]
"react-native": "0.52.0",
"react-native-autoheight-webview": "^0.4.0",

当有两个react-native-autoheight-webview 时，并且有图片显示的情况下，其中有一个加载不全？获取高度不对

**Comment by iou90** [comment]
@calvinkei merged MutationObserver at 0.5.0

**Comment by xhw1993** [comment]
@gzLonglilin how do you solve this issue, please tell me in detail, thank you!
