### ISSUE TITLE
[Android] "RCTAutoHeightWebView" does not exist

### ISSUE THREAD

**Issue by calcal12** [iou90/react-native-autoheight-webview#39]
Error: Invariant Violation: Invariant Violation: Native component for "RCTAutoHeightWebView" does not exist

Works fine for iOS, already run `react-native link react-native-autoheight-webview`

**Comment by calcal12** [comment]
Solved by adding
`import com.dscj.autoheightwebview.AutoHeightWebViewPackage;` and
`new AutoHeightWebViewPackage()`
to MainApplication.java,

should add that on README.md? will make a PR on that later

**Comment by otusweb** [comment]
@iou90 It would be great to add this in the doc. I ran into the same issue
