### ISSUE TITLE
当webview里面包含iframe的时候，会出现iframe闪烁的情况，请问有解决的办法吗？

### ISSUE THREAD

**Issue by camellieeee** [iou90/react-native-autoheight-webview#4]
RN : 0.43.0
react-native-autoheight-webview : 0.2.1
IOS : 10.2 iphone7p (emulator)
包含视频的代码如下：
`<p><iframe src="http://v.qq.com/iframe/player.html?vid=w03763itrnq&amp;tiny=0&amp;auto=0" frameborder="0" allowfullscreen="" width="330" height="249"></iframe></p>`
gif：
![webviewvideobug](https://cloud.githubusercontent.com/assets/18331008/25838363/4e712a56-34c5-11e7-937e-0f6adc28e66e.gif)

**Comment by iou90** [comment]
only occurred on iOS & 0.2.2 fixed it.
note that it can not get height when there are only text objects in a html body which does not make any sense.

**Comment by camellieeee** [comment]
<img width="486" alt="d0d944f7-ac5c-4775-beed-81dd23162aa9" src="https://cloud.githubusercontent.com/assets/18331008/25883024/ed318064-3579-11e7-8a53-e2f3f12a73d4.png">
Saved !

**Comment by iou90** [comment]
please try 0.3.0 to test the iframe issue =v=

**Comment by iou90** [comment]
fix it with 0.3.4 which has hasIframe property to use a specific script for it on iOS
