### ISSUE TITLE
customScript not working in Android.

### ISSUE THREAD

**Issue by chixpc123** [iou90/react-native-autoheight-webview#46]
Hello there,

I'm using..
`    "react": "16.2.0", `
`    "react-native": "0.53.0",`
`    "react-native-autoheight-webview": "^0.5.1"`
I'm changing font size, color and line height on press some button like.. you an show in 
https://lh3.googleusercontent.com/cdza3OdD0M_1wTm6zEjTTiSjRhyC20YI9w5NIm1NJTcOtaWpQoy5h8p_XZTccyNRbpg=h900-rw image.

I'm using your package and it's working fine for me, (after changed 4-5 libraries).
but when i check it in android, any scripts not working.
I tried your demo code of App.js, on press change script, it's not showing blue background color. so, even your demo code didn't worked for me.
so, please help.
Thanks.

**Comment by iou90** [comment]
// change script (have to change source to reload on android)
customScript={`document.body.style.background = 'lightyellow';`}

Please read the README.md carefully.

**Comment by liaojikunwork** [comment]
Hi
I am using your package on my project, but it's not working on android.

const style1 = `
    p {
        font-size: 16px !important;
        box-sizing: border-box;
    }
`;
const autoHeightScript = `
var styleElement = document.createElement('style');
styleElement.innerHTML = '${style1
  .replace(/\'/g, "\\'")
  .replace(/\n/g, "\\n")}';
document.head.appendChild(styleElement);
`;

Please help me asap.
