### ISSUE TITLE
startInLoadingState is not working

### ISSUE THREAD

**Issue by yogipriyo** [iou90/react-native-autoheight-webview#5]
I tried adding startInLoadingState prop but it is not working. Is there any way that will allow me to use that props?

![image](https://cloud.githubusercontent.com/assets/855407/26053458/15fc0c54-3993-11e7-93b0-f57067bc84a9.png)

Thank you.

**Comment by iou90** [comment]
If enable animation (by default), the opacity of Animated.View keeps 0 until the height gets calculated. enableAnimation={false}

**Comment by yogipriyo** [comment]
thank you, I got it working for iOS but Android is still not showing the loading indicator.

I add the props here : 
![image](https://cloud.githubusercontent.com/assets/855407/26093150/d6b9e172-3a3e-11e7-9aa1-969c6b80e598.png)

Is it correct or did I get it wrong?

**Comment by iou90** [comment]
@yogipriyo RCTAutoHeightWebView dose not implement all props of WebView.android.js, just part of it, if you want this feature, you can consult the WebView.android.js of React Native.
