### ISSUE TITLE
CSS color somehow not applied?

### ISSUE THREAD

**Issue by fortinmike** [iou90/react-native-autoheight-webview#50]
Hi,

We've been trying out this component in our app but we've encountered a weird issue with it: applying custom CSS to change the text color never seems to work. However, all other CSS attributes work as expected. Here is how we use it:

```javascript
import React from "react";
import PropTypes from "prop-types";
import AutoHeightWebView from "react-native-autoheight-webview";

import Colors from "@common/colors";

class RichText extends React.Component {
  static defaultProps = {
    htmlStyle: `* { color: 'red'; font-size: 16; font-family: 'arial'; }`
  };
  render() {
    return (
      <AutoHeightWebView
        source={{ html: this.props.html }}
        customStyle={this.props.htmlStyle}
        scrollEnabled={false}
        style={[this.props.style, { width: this.props.width }]}
      />
    );
  }
}

RichText.propTypes = {
  width: PropTypes.number.isRequired,
  html: PropTypes.string,
  htmlStyle: PropTypes.string,
  style: PropTypes.any
};

export default RichText;

```

The HTML we pass to this component is the following:

```html
<p>Lorem ipsum dolor sir amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</p>
```

I would expect this setup to lead to red text (see default props), but it always stays black (BUT the `font-size` and `font-family` are applied correctly!). Any idea what might be causing this?

**Comment by iou90** [comment]
color: red

**Comment by fortinmike** [comment]
Oh my god, this is such a silly mistake! I guess working with React Native stylesheets is messing with my CSS reflexes.

Sorry for wasting your time and thanks making this component available!
