### ISSUE TITLE
How to use onNavigationStateChange?

### ISSUE THREAD

**Issue by janulius** [iou90/react-native-autoheight-webview#54]
<AutoHeightWebView style={styles.webview}
                                   ref={'WEBVIEW_REF'}
                                   onNavigationStateChange={this._onNavigationStateChange.bind(this)} //for Android
                                   source={{html: html}} />

version = ( "react-native-autoheight-webview": "0.4.0" )

onNavigationStateChange not working in my app

**Comment by V1sk** [comment]
I have the same issue! On iOS, I found it is overwrite the onNavigationStateChange function, But i don't know how to make onNavigationStateChange work on Android.

**Comment by iou90** [comment]
please try @0.10.0
