### ISSUE TITLE
I added it, like this, but nothing is displayed, rn version is 0.55

### ISSUE THREAD

**Issue by ShaoGongBra** [iou90/react-native-autoheight-webview#55]
<AutoHeightWebView
                        onHeightUpdated={height => console.warn(height)}
                        // if page contains iframe on iOS, use a specific script for it
                        hasIframe={true}
                        /*
                        if set to false may cause some layout issues (width of container not fit for screen) on android
                        if set to true may cause some layout issues (smaller font size) on iOS
                        */
                        scalesPageToFit={Platform.OS === 'android' ? true : false}
                        // baseUrl not work in android 4.3 or below version
                        enableBaseUrl={true}
                        // offset of rn webview margin 
                        heightOffset={5}
                        // default width is the width of screen
                        // if there are some text selection issues on iOS, the width should be reduced more than 15 and the marginTop should be added more than 35
                        style={{ height:500  }}
                        // enable animation by default
                        enableAnimation={true}
                        // only works on enable animation
                        animationDuration={255}
                        // or uri
                        source={{ html: this.state.body }}
                        // use local or remote files
                        files={[]}
                        // add custom CSS to the page's <head>
                        customStyle={
                            `* {
                            font-family: 'Times New Roman';
                            }
                            p {
                            font-size: 16px;
                            }`
                        }
                    />

**Comment by ShaoGongBra** [comment]
<View style={styles.container}>
                <StatusBar
                    translucent={ this.state.statusBarTranslucent }
                    backgroundColor={ this.state.statusBarTranslucent? '#d81e06': '#000' }
                />
                <Header navigation={this.props.navigation} />
                <ScrollView>
                    <View style={{padding: 10}}>
                        <Text style={{fontSize: 22, fontWeight: 'bold', color: '#2c2c2c', marginBottom: 10, lineHeight: 35}}>{this.state.newsData.title}</Text>
                        <Text>{this.state.newsData.author}  {this.state.newsData.article_time}</Text>
                    </View>
                    <AutoHeightWebView
                        onHeightUpdated={height => console.warn(height)}
                        // if page contains iframe on iOS, use a specific script for it
                        hasIframe={true}
                        /*
                        if set to false may cause some layout issues (width of container not fit for screen) on android
                        if set to true may cause some layout issues (smaller font size) on iOS
                        */
                        scalesPageToFit={Platform.OS === 'android' ? true : false}
                        // baseUrl not work in android 4.3 or below version
                        enableBaseUrl={true}
                        // offset of rn webview margin 
                        heightOffset={5}
                        // default width is the width of screen
                        // if there are some text selection issues on iOS, the width should be reduced more than 15 and the marginTop should be added more than 35
                        style={{ height:500  }}
                        // enable animation by default
                        enableAnimation={true}
                        // only works on enable animation
                        animationDuration={255}
                        // or uri
                        source={{ html: this.state.body }}
                        // use local or remote files
                        files={[]}
                        // add custom CSS to the page's <head>
                        customStyle={
                            `* {
                            font-family: 'Times New Roman';
                            }
                            p {
                            font-size: 16px;
                            }`
                        }
                    />
                    
                    {/* <HTMLView
                        value={this.state.body}
                        onLinkPress={(url) => {}}
                        stylesheet={htmlStyles}
                        style={{padding: 10}}
                        renderNode={this._renderNode}
                    /> */}
                </ScrollView>
            </View>

**Comment by ShaoGongBra** [comment]
<View style={styles.container}>
                <StatusBar
                    translucent={ this.state.statusBarTranslucent }
                    backgroundColor={ this.state.statusBarTranslucent? '#d81e06': '#000' }
                />
                <Header navigation={this.props.navigation} />
                <ScrollView>
                    <View style={{padding: 10}}>
                        <Text style={{fontSize: 22, fontWeight: 'bold', color: '#2c2c2c', marginBottom: 10, lineHeight: 35}}>{this.state.newsData.title}</Text>
                        <Text>{this.state.newsData.author}  {this.state.newsData.article_time}</Text>
                    </View>
                    <AutoHeightWebView
                        onHeightUpdated={height => console.warn(height)}
                        // if page contains iframe on iOS, use a specific script for it
                        hasIframe={true}
                        /*
                        if set to false may cause some layout issues (width of container not fit for screen) on android
                        if set to true may cause some layout issues (smaller font size) on iOS
                        */
                        scalesPageToFit={Platform.OS === 'android' ? true : false}
                        // baseUrl not work in android 4.3 or below version
                        enableBaseUrl={true}
                        // offset of rn webview margin 
                        heightOffset={5}
                        // default width is the width of screen
                        // if there are some text selection issues on iOS, the width should be reduced more than 15 and the marginTop should be added more than 35
                        style={{ height:500  }}
                        // enable animation by default
                        enableAnimation={true}
                        // only works on enable animation
                        animationDuration={255}
                        // or uri
                        source={{ html: this.state.body }}
                        // use local or remote files
                        files={[]}
                        // add custom CSS to the page's <head>
                        customStyle={
                            `* {
                            font-family: 'Times New Roman';
                            }
                            p {
                            font-size: 16px;
                            }`
                        }
                    />
                    
                    {/* <HTMLView
                        value={this.state.body}
                        onLinkPress={(url) => {}}
                        stylesheet={htmlStyles}
                        style={{padding: 10}}
                        renderNode={this._renderNode}
                    /> */}
                </ScrollView>
            </View>

**Comment by ShaoGongBra** [comment]
Finding the reason seems to be because I wrote a height above it

**Comment by iou90** [comment]
please try @0.10.0
