### ISSUE TITLE
why not use `onMessage` props ?

### ISSUE THREAD

**Issue by uinz** [iou90/react-native-autoheight-webview#6]
[https://facebook.github.io/react-native/docs/webview.html#onmessage](https://facebook.github.io/react-native/docs/webview.html#onmessage)

1. 我认为 使用 message 进行通许比 使用hash location 这种方式要好吧, 许多 SPA 是使用 hash 做路由的.

2. 建议增加一个 自定义 动态修改`height` 的触发事件 比如 `DOMContentLoaded` 或者 提供替换 BaseScript 的方法 , 因为当大量图片 或者 iframe 加载的时候 会有很长时间的空白响应, 不是很好处理.

---

我发现就算监听  `DOMContentLoaded` `DOMSubtreeModified` 事件也没办法做到在有 `<iframe />`
的情况下马上触发 updateHeight() 方法.

**Comment by iou90** [comment]
This related to this issue https://github.com/facebook/react-native/pull/10941 and if the html code include iframe node, onMessage will crash on iOS.
