### ISSUE TITLE
Can not find module when import

### ISSUE THREAD

**Issue by vietnd87** [iou90/react-native-autoheight-webview#60]
Hi there,

Please help me add index.js in root module or other way to ensure eslint & typescript import correct component dir. Current version it has error Cannot find module 'react-native-autoheight-webview' and I can not build app.

**Comment by iou90** [comment]
Does the demo works?

**Comment by vietnd87** [comment]
Yes, It still work fine, only eslint or typescript unknow import path, although I setting "moduleResolution": "node" in compilerOptions.

All other node_module work fine without your module.

**Comment by rickychowhk01** [comment]
Is works for me.

**Comment by vietnd87** [comment]
did you use typescipt? and can you send me your tsconfig.json content?

**Comment by Lichwa** [comment]
Having the same issue in `0.10.2`

**Comment by iou90** [comment]
Please try 0.10.3.
