### ISSUE TITLE
onMessage not working

### ISSUE THREAD

**Issue by thangkho** [iou90/react-native-autoheight-webview#62]
I have component: 
https://stackblitz.com/edit/react-zk4ukn

if `WebView import from react-native` function `onMessage`  will log `Hello React`  but when change it with `WebView import from 'react-native-autoheight-webview'` it not show console.log `Hello React`.
How I can get event click button from html in your WebView autoheight?

**Comment by songhanlin** [comment]
why not format your code?

**Comment by thangkho** [comment]
@songhanlin  I update my code in https://stackblitz.com/edit/react-zk4ukn

**Comment by iou90** [comment]
react-native-autoheight-webview does not support onMessage until now.

**Comment by thangkho** [comment]
@iou90  I think you need add 
`
onMessage = e => {
      const { height, width } = JSON.parse(isBelowKitKat ? e.nativeEvent.message : e.nativeEvent.data);
      if (height && height !== this.state.height && width && width !== this.state.width) {
          
      }else{
        this.props.onMessage(e)
     }
  };
`
 It will support `onMessage` event

**Comment by iou90** [comment]
please try @0.10.0
