### ISSUE TITLE
How to use tag <head> for html

### ISSUE THREAD

**Issue by thangkho** [iou90/react-native-autoheight-webview#63]
I need use 
`<**head**>
    <title>KEETOOL EDITOR</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0,height=device-height"
    />
    <meta name="format-detection" content="telephone=no">
</**head**>`
to my webview, how I can use it?

**Comment by iou90** [comment]
Just put it in your html code, what is your real problem?
