### ISSUE TITLE
OnLoad and onShouldStartLoadWithRequest func calling again and again IOS, screen flickering

### ISSUE THREAD

**Issue by ronakjain-2** [iou90/react-native-autoheight-webview#64]
Hi,

I have used this component like:

<AutoHeightWebView
        onHeightUpdated={height =>
          console.log(`height ${height}`)}
        // if page contains iframe on iOS, use a specific script for it
        hasIframe={true}
        /*
        if set to false may cause some layout issues (width of container not fit for screen) on android
        if set to true may cause some layout issues (smaller font size) on iOS
        */
        scalesPageToFit={Platform.OS === 'android' ? true : false}
        // baseUrl not work in android 4.3 or below version
        enableBaseUrl={true}
        source={{ html: `<iframe src=${'https://www.youtube.com/embed/RJa4kG1N3d0'} width="100%" height="210" frameborder="0" allowfullscreen/>` }}
        // rn WebView callbacks
        onError={() => console.log('on error')}
        onLoad={() => console.log('on load')}
        onLoadStart={() => console.log('on load start')}
        onLoadEnd={() => console.log('on load end')}
        // only on iOS
        onShouldStartLoadWithRequest={result => {
          console.log(`onShouldStartLoadWithRequest ${JSON.stringify(result)}`)
          return true;
        }}
        />

Now i am getting the onLoad function is calling again and again, console is printing 'on load' every time.
onShouldStartLoadWithRequest func also calling again and again. and the screening is flickering.

console output: 

onShouldStartLoadWithRequest {"target":1442,"canGoBack":false,"lockIdentifier":3465593839,"loading":false,"title":"","canGoForward":false,"navigationType":"other","url":"file:///Users/ronakjain/Library/Developer/CoreSimulator/Devices/792400B3-EA47-429A-8A6C-14D1618E6DBA/data/Containers/Bundle/Application/17E26A2B-C231-4F42-8243-3055E320A855/PrettySecrets.app/web"}
logger.js:14 on load start
logger.js:14 onShouldStartLoadWithRequest {"target":1442,"canGoBack":false,"lockIdentifier":754468582,"loading":true,"title":"","canGoForward":false,"navigationType":"other","url":"https://www.youtube.com/embed/RJa4kG1N3d0"}
logger.js:14 onShouldStartLoadWithRequest {"target":1442,"canGoBack":false,"lockIdentifier":230375066,"loading":true,"title":"","canGoForward":false,"navigationType":"other","url":"about:blank"}
logger.js:14 onShouldStartLoadWithRequest {"target":1442,"canGoBack":false,"lockIdentifier":2063609916,"loading":true,"title":"","canGoForward":false,"navigationType":"other","url":"https://www.youtube.com/embed/RJa4kG1N3d0"}
logger.js:14 onShouldStartLoadWithRequest {"target":1442,"canGoBack":false,"lockIdentifier":3358159173,"loading":true,"title":"210","canGoForward":false,"navigationType":"other","url":"file:///Users/ronakjain/Library/Developer/CoreSimulator/Devices/792400B3-EA47-429A-8A6C-14D1618E6DBA/data/Containers/Bundle/Application/17E26A2B-C231-4F42-8243-3055E320A855/PrettySecrets.app/web#1"}
logger.js:14 on load start
logger.js:14 on load
logger.js:14 on load end
logger.js:14 height 210
logger.js:14 onShouldStartLoadWithRequest {"target":1442,"canGoBack":false,"lockIdentifier":2570092979,"loading":true,"title":"210","canGoForward":false,"navigationType":"other","url":"about:blank"}
logger.js:14 onShouldStartLoadWithRequest {"target":1442,"canGoBack":false,"lockIdentifier":4041732970,"loading":true,"title":"210","canGoForward":false,"navigationType":"other","url":"https://www.youtube.com/embed/RJa4kG1N3d0"}
logger.js:14 on load
logger.js:14 on load end
logger.js:14 onShouldStartLoadWithRequest {"target":1442,"canGoBack":false,"lockIdentifier":2205232811,"loading":true,"title":"210","canGoForward":false,"navigationType":"other","url":"about:blank"}
logger.js:14 onShouldStartLoadWithRequest {"target":1442,"canGoBack":false,"lockIdentifier":291925839,"loading":true,"title":"210","canGoForward":false,"navigationType":"other","url":"https://www.youtube.com/embed/RJa4kG1N3d0"}
logger.js:14 on load
logger.js:14 on load end
logger.js:14 onShouldStartLoadWithRequest {"target":1442,"canGoBack":false,"lockIdentifier":314753191,"loading":true,"title":"210","canGoForward":false,"navigationType":"other","url":"about:blank"}
logger.js:14 onShouldStartLoadWithRequest {"target":1442,"canGoBack":false,"lockIdentifier":1844513979,"loading":true,"title":"210","canGoForward":false,"navigationType":"other","url":"https://www.youtube.com/embed/RJa4kG1N3d0"}
logger.js:14 on load
logger.js:14 on load end
logger.js:14 onShouldStartLoadWithRequest {"target":1442,"canGoBack":false,"lockIdentifier":2937000452,"loading":true,"title":"210","canGoForward":false,"navigationType":"other","url":"about:blank"}
logger.js:14 onShouldStartLoadWithRequest {"target":1442,"canGoBack":false,"lockIdentifier":3690577104,"loading":true,"title":"210","canGoForward":false,"navigationType":"other","url":"https://www.youtube.com/embed/RJa4kG1N3d0"}
logger.js:14 on load
logger.js:14 on load end
logger.js:14 onShouldStartLoadWithRequest {"target":1442,"canGoBack":false,"lockIdentifier":2175068525,"loading":true,"title":"210","canGoForward":false,"navigationType":"other","url":"about:blank"}
logger.js:14 onShouldStartLoadWithRequest {"target":1442,"canGoBack":false,"lockIdentifier":3878204594,"loading":true,"title":"210","canGoForward":false,"navigationType":"other","url":"https://www.youtube.com/embed/RJa4kG1N3d0"}
logger.js:14 on load
logger.js:14 on load end

Note: It was working fine around 1-2 months back.

**Comment by iou90** [comment]
`<iframe src=${'https://www.youtube.com/embed/RJa4kG1N3d0'} width="100%" height="210" frameborder="0" allowfullscreen></iframe>`
use the closed tag of iframe.
