### ISSUE TITLE
Open links in browser

### ISSUE THREAD

**Issue by hirani89** [iou90/react-native-autoheight-webview#66]
Is it possible to open links in browser instead of webview?

I tried the code below but no luck.
```
onNavigationStateChange={(event) => {
                             if (event.url !== uri) {
                               this.webview.stopLoading();
                               Linking.openURL(event.url);
                             }
                           }}
```

**Comment by vietnd87** [comment]
Same problem too

**Comment by iou90** [comment]
Same issue as #19 ?

**Comment by AtixD** [comment]
@iou90 Hi, please fix it
index.ios.js
`
  stopLoading() {
    this.webView.stopLoading();
  }
`
to
`
  stopLoading() {
    this.webView.current.stopLoading();
  }
`

thx

**Comment by vietnd87** [comment]
@iou90  Can you update onMessage and onNavigationStateChange props for version 0.6.1? Follow your document, my react-native version is 0.55 and I can not use two props.

**Comment by vivianlam926** [comment]
any solutions for open link in browser for android?

**Comment by iou90** [comment]
@vietnd87 Sorry for having no time to maintain multiple versions, you can fork it to fit your needs.

**Comment by iou90** [comment]
https://medium.com/@elhardoum/opening-external-links-in-browser-in-react-native-webview-18fe6a66312a
Anyone try this solution?

**Comment by otusweb** [comment]
For the next person to see this bug. This is what I use. Notice the forceUpdate to reset the component and not load the link:
```


  handleLoadStart = (event: any) => {
    let url = event.nativeEvent.url;
    if (url.startsWith("http")) {
      Linking.canOpenURL(url).then(supported => {
        if (supported) {
          Linking.openURL(url);
        } else {
          logError("unsupported URL to open", this.props.message);
        }
      });
      this.forceUpdate();

      return false;
    } else {
      return true;
    }
  };
```

**Comment by iou90** [comment]
It should works both on iOS & Android with @0.10.5, please check the demo.
