### ISSUE TITLE
 AutoHeightWebViewPackage is not abstract and does not override abstract method createJSModules() in ReactPackage

### ISSUE THREAD

**Issue by thangkho** [iou90/react-native-autoheight-webview#67]
when I install your lib it show error
`D:\reactex\react-native-htv\HoatvRn\node_modules\react-native-autoheight-webview\android\src\main\java\com\dscj\autoheightwebview\AutoHeightWebViewPackage.java:13: error: AutoHeightWebViewPackage is not abstract and does not override abstract method createJSModules() in ReactPackage
public class AutoHeightWebViewPackage implements ReactPackage {
       ^
1 error`
after that I open you lib android and see your folder pakage is `java/com/dscj/autoheightwebview` but in your `AndroidManifest.xml` you set ` package="com.iou90.autoheightwebview"` .
Please change your package in `AndroidManifest` or change name of folder in your lib
And in `AutoHeightWebViewPackage` you can add ` @Override`  `createJSModules()` method for your missing implement?

**Comment by iou90** [comment]
Can you run the demo in the repo?

**Comment by thangkho** [comment]
I can run it if I change `package="com.iou90.autoheightwebview"` in `AndroidManifest` and add `createJSModules`  in `AutoHeightWebViewPackage .java` with android studio.

**Comment by iou90** [comment]
Cause of removing unused createJSModules calls in React Naitve 0.47 (https://github.com/facebook/react-native/releases/tag/v0.47.2), please install react-native-autoheight-webview 0.3.1 for the project with 0.44 <= rn < 0.47.

But the rn version of the demo is 0.56.0, what is your environment?

**Comment by weixiaoqing** [comment]
我要把RN版本降低到0.47以下？现在是0.56报这个错误

**Comment by iou90** [comment]
Can you run the demo?

在 2018年8月31日，09:03，weixiaoqing <notifications@github.com<mailto:notifications@github.com>> 写道：


我要把RN版本降低到0.47以下？现在是0.56报这个错误

**Comment by iou90** [comment]
0.10.6 should fix it.
