### ISSUE TITLE
ios内存泄露问题

### ISSUE THREAD

**Issue by fangkyi03** [iou90/react-native-autoheight-webview#70]
ios会出现内存泄露问题在你接管
window.resize = updateSize
以后 当你改变高度的时候 这个动画就会被调用 然后又会重复调用 直到死循环耗尽内存

**Comment by iou90** [comment]
The code actually do 
`
window.addEventListener('load', updateSize);
window.addEventListener('resize', updateSize);
`
What is your real problem? What is your html source?
