### ISSUE TITLE
OnSizeUpdated not updating width

### ISSUE THREAD

**Issue by ShaMan123** [iou90/react-native-autoheight-webview#72]
I've noticed you merged my PR!
So I tried using the updated master.

### First issue:
Is the npm package outdated? I tried installing and got a stale version of the code.
So I went on and pulled directly from the repo.

----

## Main issue:

Platform: Android (6.0.1)

### Expected Behavior
**used my fork to run this**

![Expected Behavior](https://user-images.githubusercontent.com/34343793/44296077-eb9a2080-a2bf-11e8-82c7-69bc7f7901ab.png)

### log output of `onSizeUpdated` 
![log-expected](https://user-images.githubusercontent.com/34343793/44296297-d4a9fd00-a2c4-11e8-9abd-7071820089a0.png)

----

### Actual Behavior
**used the master to run this**

![Actual Behavior](https://user-images.githubusercontent.com/34343793/44296076-eb9a2080-a2bf-11e8-8437-949d2ca9773d.png)

### log output of `onSizeUpdated` -> you can see the width does not change.

![log](https://user-images.githubusercontent.com/34343793/44296205-682dfe80-a2c2-11e8-9d20-62d19b4569cf.png)

---

I'll try looking in to it (Hope I have the time).

Thanks

**Comment by ShaMan123** [comment]
Hard to debug :(

**For now**:
I've found that some method is calling `setState` somewhere (not in `componentDidUpdate`) repeatedly in isn't stopping.

**Comment by iou90** [comment]
Your pr was using a prop to modified body style which is unacceptable, it now will watch the changing of the width of inline element.
Can you provide your html source?

**Comment by ShaMan123** [comment]
Thanks for that!
I didn't realize that the body style was rejected from the PR.
Changed it in my code (passed down a `customStyle`) and **everything works perfectly**.

**Many thanks!!**

**Comment by ShaMan123** [comment]
closing

**Comment by ShaMan123** [comment]
I will mention for others:
If there are some problems with the width causing the `WebView` to overflow try wrapping your `html` with an element and styling that element with `padding`:

```

getHTML(innerHTMLString) {
       return `<span style="padding: 0 10px;">${innerHTMLString}</span>`
}
```
