### ISSUE TITLE
0.61  ios  加载 files 直接webview不显示了

### ISSUE THREAD

**Issue by lihongtao2012** [iou90/react-native-autoheight-webview#75]
return (<AutoHeightWebView
            enableAnimation={false}
            scalesPageToFit={false}
            baseUrl={Platform.OS === 'android' ? 'file:///android_asset/web/' : 'web/'}
            files={[
                {
                    href: 'question_style.css',
                    type: 'text/css',
                    rel: 'stylesheet'
                }
            ]}
            style={{width:GlobalStyles.width-32}}
            key={this.state.urls}
            source={{html: this.state.item}}
        />)

    "react-native": "^0.54.4",
    "react-native-autoheight-webview": "^0.6.1",

<img width="357" alt="2018-08-24 11 14 31" src="https://user-images.githubusercontent.com/7009005/44563092-34098080-a78f-11e8-97a5-7e77662e2180.png">

**Comment by iou90** [comment]
Can you run the demo in the repo?
