### ISSUE TITLE
0.6.1 ios很卡

### ISSUE THREAD

**Issue by keyWung** [iou90/react-native-autoheight-webview#76]
0.6.1ios很卡，而且底部出现很多留白区域

**Comment by iou90** [comment]
Please use the last version, thanks.

**Comment by keyWung** [comment]
Do the last version support react native@0.54.0 or low version?

**Comment by iou90** [comment]
No, sorry.

在 2018年8月29日，13:48，keyWung <notifications@github.com<mailto:notifications@github.com>> 写道：


Do the last version support react native@0.54.0 or low version?
