### ISSUE TITLE
Android error - requireNativeComponent: 'RCTAutoHeightWebView' was not found in the UIManager

### ISSUE THREAD

**Issue by dsditt** [iou90/react-native-autoheight-webview#77]
This is working fine in iOS, but on Android I'm getting the error described in the title. Using 0.10.2 of the plugin, 0.56 of React Native.

The issue appears to be triggered around the node_modules/react-native-autoheight-webview/autoHeightWebView/index.android.js line 32: 

const RCTAutoHeightWebView = requireNativeComponent('RCTAutoHeightWebView', AutoHeightWebView,...

Seems like it can't find anything which matches that ''RCTAutoHeightWebView' string. 

Any suggestions? I've tried relinking, readding the plugin, as well as cleaning my gradle wrapper which haven't helped so far.

**Comment by dsditt** [comment]
Yeah, I'm able to run the demo on iOS and the Android device my app is crashing on.

I'm not really sure what the problem is. The error occurs while calling requireNativeComponent in index.android.js in your plugin directory within node_modules. Any thoughts as to what might cause that or something I can try next?

**Comment by iou90** [comment]
Please pay attention to the Readme.

> You may have to copy autoHeightWebView, android, node_modules folders to 'demo/node_modules/react-native-autoheight-webview/', cause of installing a local package with npm will create symlink, but there is no supporting of React Native to symlink (https://github.com/facebook/watchman/issues/105).

**Comment by maxammann** [comment]
Having the same message.

**Comment by dsditt** [comment]
Doesn't fix for me. I've tried relinking, removing and readding. When I try to link I get a message that I'm already linked - 

`Platform 'android' module react-native-autoheight-webview is already linked 
`

**Comment by iou90** [comment]
https://github.com/iou90/react-native-autoheight-webview/issues/81#issuecomment-422245823
FYI @dsditt

**Comment by iou90** [comment]
> Please check 0.11.0 which is a pure js version for Android (no native module).

FYI @dsditt
