### ISSUE TITLE
如何跳转到外部（手机默认）浏览器

### ISSUE THREAD

**Issue by ZhangTaoK** [iou90/react-native-autoheight-webview#79]
WebView可以自定义injectedJavaScript属性设置以下内容拦截a标签，点击从外部打开。
`
        var a = document.getElementsByTagName('a');
        for(var i = 0; i < a.length; i++){
            a[i].onclick = function (event) {
                window.postMessage(this.href);
                event.preventDefault();
            }
        }
    `
_onMessage = (e) => {
        Linking.openURL(e.nativeEvent.data).catch(err => console.error('An error occurred', err))
    }

请问，我们这个组件，需要如何设置？

**Comment by ZhangTaoK** [comment]
customScript需要设置什么样的值？

**Comment by iou90** [comment]
#19
