### ISSUE TITLE
Is it compatable with expo?

### ISSUE THREAD

**Issue by mrded** [iou90/react-native-autoheight-webview#81]
Hi,

We are writing our apps using [Expo](https://expo.io/). And this module seems to require a native integration for Android, which is not possible with using Expo.

As I can say, the ios version works well as it's, and Android is crashing with the following error:

> Invariant Violation: Native component for "RCTAutoHeigtWebView" does not exist

Is there a way to use the module with Expo without a native integration?

**Comment by iou90** [comment]
May be it's the time to make a pure js version for Android depends on onMessage prop.
But currently I'm too busy to implement this & welcome PR!

**Comment by longunibbo** [comment]
Have you release a fix for Expo?

**Comment by iou90** [comment]
Please check 0.11.0 which is a pure js version for Android (no native module).
