### ISSUE TITLE
stopLoading is not a function

### ISSUE THREAD

**Issue by otusweb** [iou90/react-native-autoheight-webview#82]
RN 0.56
autoheight webview: 0.10.2

If I call stop loading on an autoheight webview, I get the following error 
<img width="447" alt="screen shot 2018-09-11 at 15 16 57" src="https://user-images.githubusercontent.com/1069914/45362682-c1ddcc00-b5d5-11e8-831b-b6732c97a3a6.png">

printing this.webView in common.ios.js prints:
{current: WebView}

So I think the stopLoading method should change to:
this.webView.current.stopLoading();

But even modifying this does not seem to stop the page from loading...

**Comment by iou90** [comment]
Fixed in 0.10.3.
