### ISSUE TITLE
Android no render. 

### ISSUE THREAD

**Issue by Just013** [iou90/react-native-autoheight-webview#86]
i already linked...
Terminal: info: Platform 'android' module react-native-autoheight-webview is already linked 
iOS no problem

**Comment by iou90** [comment]
No render? More details?

**Comment by Just013** [comment]
i can,t see the webView.




------------------ 原始邮件 ------------------
发件人: "iou90"<notifications@github.com>;
发送时间: 2018年10月11日(星期四) 中午11:18
收件人: "iou90/react-native-autoheight-webview"<react-native-autoheight-webview@noreply.github.com>;
抄送: "0 1 3"<497047791@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [iou90/react-native-autoheight-webview] Android no render.  (#86)




No render? More details?

**Comment by kevin611003** [comment]
same, IOS is normal, Android is not work
after add width & height to the AutoHeightWebView, i can see it, but setting customStyle & customScript  does not work

**Comment by notjiam** [comment]
I'm not sure it same my issue.

My issue when I set style={{ width: ... }} 
In android some case I update state.height with null

I create pull request at 
https://github.com/iou90/react-native-autoheight-webview/pull/88

**Comment by iou90** [comment]
Should be fixed at @0.10.4
