### ISSUE TITLE
goBack is not a function

### ISSUE THREAD

**Issue by zggb** [iou90/react-native-autoheight-webview#90]
tnx, for your excellent lib.
unfortunately, I have a bug, that cannot be resolved by myself

Android
RN 0.57
autoheight webview: 0.10.4

I have undefined goBack() function because it missed in reference. It's missed only on Android, on Ios I can use current property smth like this.refs[webViewref].current.goBack()

<img width="313" alt="screen shot 2018-10-29 at 5 57 43 pm" src="https://user-images.githubusercontent.com/8955744/47664595-0f26f480-dba8-11e8-8b4b-1f6295fe77a3.png">

<img width="905" alt="screen shot 2018-10-29 at 6 28 56 pm" src="https://user-images.githubusercontent.com/8955744/47664875-9d02df80-dba8-11e8-8129-943b8996055d.png">

**Comment by iou90** [comment]
This function was not implemented and I think it's nothing related to the auto height feature.
