### ISSUE TITLE
Android minimal version (api)?

### ISSUE THREAD

**Issue by omgo** [iou90/react-native-autoheight-webview#91]
Hello! I tried demo on some android versions, it's not working on android 5.0 (6.0+ is ok), but I need this version. No way?
Thank you

**Comment by iou90** [comment]
Honestly I have no idea why it not works with android 5.0.
I will try the implement of 0.6.1 with rn 0.57 later.

**Comment by iou90** [comment]
The last version (0.11.0) removed native module and using rn Webview & the Android minimal version is 4.4 (api 19) and auto width for inline html will not work on Android 5.1  and below (api 22).
