### ISSUE TITLE
[Android] Crash when using Chrome WebView Engine

### ISSUE THREAD

**Issue by replecta** [iou90/react-native-autoheight-webview#94]
Awesome lib. However if android's default web view engine is Chrome instead of Android System WebView, it crashes the app. I had to go to the developer's tools and change it in WebView implementation.

Currently running on Android Pie (9.0) on React Native (0.57.7)

**Comment by iou90** [comment]
What's the version of Chrome WebView of your environment?
Chrome 66.0.3359.158 on x86_64 Android Pie simulator can not reproduction this issue.

**Comment by iou90** [comment]
Still could not reproduction on emulator (api28, Android Pie) or device (Nexus 6P, Android 8.1) with Chrome WebView 71.0.3578.99.
I have tested by using rn webview or the webview within the lib, so does the issue exists using rn webview on your device?

**Comment by lucas-coelho** [comment]
I think is the same problem: https://github.com/react-native-community/react-native-webview/issues/429
