### ISSUE TITLE
Use react-native-webview

### ISSUE THREAD

**Issue by bsnelder** [iou90/react-native-autoheight-webview#95]
Since the webview is going to be removed from the React Native core I think it's good to update this package to use https://github.com/react-native-community/react-native-webview. 

This library is under active development and it also includes some nice updates like onShouldStartLoadWithRequest support for Android.

Also see the Warning in the react native docs: https://facebook.github.io/react-native/docs/webview

BTW thanks for this nice package!

**Comment by FullstackJack** [comment]
Will this break apps using WebView in Expo? Has Expo moved to `react-native-webview`? This is a major breaking change.

**Comment by iou90** [comment]
@FullstackJack Not yet, https://docs.expo.io/versions/latest/react-native/webview/

**Comment by FullstackJack** [comment]
I agree that it should eventually be upgraded but if you plan to do this before Expo gets around to it, please bump major and maintain both versions with patchs.

**Comment by FullstackJack** [comment]
I hate to break it to you, but `https://github.com/scazzy/react-native-webview-autoheight/` is working better and seems to be less code. I wonder what is the difference, I haven't parsed the two approaches. My code involves taking a wild west of HTML/JS embeds and waiting for the widget to finish loading before updating the height. When I used your plugin, it didn't wait for Twitter Embed to finish loading the image before setting the height so it cut off a ton of the widget. Not sure how to make this one better.

**Comment by FullstackJack** [comment]
Here, try this Tweet as HTML source.

```
<div class="wp-block-embed__wrapper">
<blockquote class="twitter-tweet" data-width="525" data-dnt="true"><p lang="en" dir="ltr">Please go vote! Preferably against all Trump allies complicit in his Racist, Misogynist, Xenophobic, Homophobic, Transphobic and all around fear based agenda.  Hope lives! 🇺🇸 ❤️ 🌈  ✊🏽 <a href="https://t.co/vzCm6laAKO">pic.twitter.com/vzCm6laAKO</a></p>— Conor Oberst (@conoroberst) <a href="https://twitter.com/conoroberst/status/1059877792299565057?ref_src=twsrc%5Etfw">November 6, 2018</a></blockquote><script async="" src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
</div>
```

**Comment by iou90** [comment]
Using react-native-webview with 1.0.0.
