### ISSUE TITLE
Auto Width on Android

### ISSUE THREAD

**Issue by linh232323** [iou90/react-native-autoheight-webview#97]
Hello,

I tried version 0.6.1 with scalesPageToFit but page content is not fit. 
My content is always outside of view port.
Could u please show me instruction how to do it ?

Thanks and best regards,

**Comment by iou90** [comment]
Can you use 0.11.0 ?

**Comment by linh232323** [comment]
Hi @iou90 ,

I have tried to use 0.11.0, but got the following issue from Android adb logcat:

`com.facebook.react.common.JavascriptException: null is not an object (evaluating 'e.webView.current.postMessage'), stack`

Do you know how to fix it ? i used React Native 0.50.3

Thanks and best regards,
Linh.Ho

**Comment by iou90** [comment]
@linh232323 FYI:
Cause of changes to lifecycle methods in React 16.3.0 (https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html), please install react-native-autoheight-webview 0.6.1 for the project with 0.47 <= rn < 0.55
