### ISSUE TITLE
Does 0.11.0 support android installation？

### ISSUE THREAD

**Issue by cw19920617** [iou90/react-native-autoheight-webview#98]

**Comment by iou90** [comment]
What do you mean about android installation?

**Comment by elmotan95** [comment]
> > What do you mean about android installation?
> 
> link failed

You don't need to link, it's for version 0.10.6 and below (as stated in readme).
If you upgrade from previous version, just remove manually linked code in `MainApplication.java`, `settings.gradle` and `app/build.gradle`
