### ISSUE TITLE
iOS Font Family cannot be replace to san-serif

### ISSUE THREAD

**Issue by indragawe73** [iou90/react-native-autoheight-webview#99]
Hi Giys, I have to replace the font-family webVIew in iOS from 'Time New Romance' to 'san-serif'
and this is my Setup : 

 <AutoHeightWebView
                                style={{ width: Dimensions.get('window').width - 15, marginTop: 35 }}
                                customScript={`document.body.style.background = '#fff';`}
                                customStyle={`
                                  * {
                                    font-family: 'sans-serif';
                                  }
                                  p {
                                    font-size: 16px;
                                  }
                                `}
                                enableAnimation={false}
                                animationDuration={255} 
                                heightOffset={5}
                                onMessage={e => console.log(e)}
                                scalesPageToFit={Platform.OS === 'Android' ? true : false}
                                source={{ html: htmlContent }}
                                onError={() => console.log('on error')}
                                onLoad={() => console.log('on load')}
                                onLoadStart={() => console.log('on load start')}
                                onLoadEnd={() => console.log('on load end')}
                                scrollEnabled={true}
                                hasIframe={true}
                                onShouldStartLoadWithRequest={result => { 
                                  console.log(result)
                                  return true;
                                }}
                              />

**Comment by iou90** [comment]
font-family: sans-serif;
